export type Level = "A1" | "A2" | "B1";
export type Lesson = {
  id: string;
  level: Level;
  group: string;
  title: string;
  objective: string;
  rule: string;
  examples: [string, string][];
  keywords: string[];
};

export type CourseExercise = {
  id: string;
  level: Level;
  skill: "Vocabulaire" | "Grammaire" | "Verbes" | "Communication" | "Temps";
  mode: "choice" | "fill" | "reorder" | "transform";
  prompt: string;
  answer: string;
  options?: string[];
  tokens?: string[];
  hint: string;
};

export type TcfTaskId = "tache1" | "tache2" | "tache3";
export type TcfDrill = { task: TcfTaskId; prompt: string; answer: string; options: string[]; note: string };

export const lessons: Lesson[] = [
  {id:"a1-alphabet",level:"A1",group:"Premiers repères",title:"Alphabet et sons",objective:"Épeler un nom et reconnaître les principaux sons français.",rule:"En français, le nom des lettres et certains sons nasaux demandent une écoute attentive.",examples:[["Comment ça s’écrit ?","¿Cómo se escribe?"],["Ça s’écrit M-A-R-I-E.","Se escribe M-A-R-I-E."]],keywords:["alphabet","épeler","accents","sons nasaux"]},
  {id:"a1-nombres",level:"A1",group:"Premiers repères",title:"Nombres et quantités",objective:"Comprendre et produire les nombres utiles au quotidien.",rule:"Mémorisez les blocs 0-20, les dizaines, puis les constructions particulières 70, 80 et 90.",examples:[["J’ai trente-deux ans.","Tengo 32 años."],["Ça coûte quatre-vingt-dix dollars.","Cuesta 90 dólares."]],keywords:["0-100","prix","téléphone","âge"]},
  {id:"a1-calendrier",level:"A1",group:"Premiers repères",title:"Jours, mois et saisons",objective:"Donner une date et situer un événement dans l’année.",rule:"Les jours et les mois s’écrivent normalement sans majuscule en français.",examples:[["Nous sommes lundi 12 mai.","Es lunes 12 de mayo."],["Mon anniversaire est en hiver.","Mi cumpleaños es en invierno."]],keywords:["semaine","mois","date","saisons"]},
  {id:"a1-saluer",level:"A1",group:"Se présenter",title:"Saluer et prendre congé",objective:"Choisir une formule adaptée à une situation formelle ou familière.",rule:"Utilisez « tu » avec les proches et « vous » dans une situation formelle.",examples:[["Bonjour, comment allez-vous ?","Buenos días, ¿cómo está?"],["Salut, à bientôt !","Hola, ¡hasta pronto!"]],keywords:["bonjour","salut","au revoir","vous"]},
  {id:"a1-etre",level:"A1",group:"Se présenter",title:"Le verbe être",objective:"Présenter son identité, sa situation et une caractéristique.",rule:"Je suis, tu es, il/elle est, nous sommes, vous êtes, ils/elles sont.",examples:[["Je suis argentine.","Soy argentina."],["Nous sommes étudiants.","Somos estudiantes."]],keywords:["être","identité","état","présent"]},
  {id:"a1-genre",level:"A1",group:"Se présenter",title:"Masculin et féminin",objective:"Accorder les adjectifs avec la personne décrite.",rule:"On ajoute souvent -e au féminin, mais plusieurs formes sont irrégulières.",examples:[["Il est sportif.","Él es deportista."],["Elle est sportive.","Ella es deportista."]],keywords:["adjectifs","accord","masculin","féminin"]},
  {id:"a1-identite",level:"A1",group:"Se présenter",title:"Nationalité, profession et statut",objective:"Décrire les informations essentielles d’une personne.",rule:"Après « être », la profession s’utilise généralement sans article.",examples:[["Elle est médecin.","Ella es médica."],["Il est canadien et célibataire.","Él es canadiense y soltero."]],keywords:["nationalité","profession","marié","célibataire"]},
  {id:"a1-prepositions",level:"A1",group:"Se présenter",title:"À, de et chez",objective:"Indiquer un lieu, une origine ou la maison d’une personne.",rule:"À indique souvent la destination; de, l’origine; chez, le lieu associé à une personne.",examples:[["Je vais à Montréal.","Voy a Montreal."],["Je dîne chez Paul.","Ceno en casa de Paul."]],keywords:["à","de","chez","lieux"]},
  {id:"a1-heure",level:"A1",group:"Se présenter",title:"Dire l’heure",objective:"Demander et indiquer l’heure avec précision.",rule:"On dit « Il est… heure(s) », avec et quart, et demie ou moins le quart.",examples:[["Il est huit heures et demie.","Son las ocho y media."],["À quelle heure commence le cours ?","¿A qué hora empieza el curso?"]],keywords:["heure","quart","demie","horaire"]},
  {id:"a1-possessifs",level:"A1",group:"Se présenter",title:"Les possessifs",objective:"Exprimer l’appartenance en accordant avec l’objet possédé.",rule:"Mon/ma/mes, ton/ta/tes, son/sa/ses s’accordent avec le nom qui suit.",examples:[["C’est mon livre.","Es mi libro."],["Voici leurs enfants.","Aquí están sus hijos."]],keywords:["mon","ma","mes","appartenance"]},
  {id:"a1-avoir",level:"A1",group:"Avoir et demander",title:"Le verbe avoir",objective:"Parler de possession, d’âge et de besoins courants.",rule:"J’ai, tu as, il/elle a, nous avons, vous avez, ils/elles ont.",examples:[["J’ai une voiture.","Tengo un automóvil."],["Nous avons faim.","Tenemos hambre."]],keywords:["avoir","âge","faim","soif"]},
  {id:"a1-articles",level:"A1",group:"Avoir et demander",title:"Articles définis et indéfinis",objective:"Choisir entre un élément identifié et un élément présenté pour la première fois.",rule:"Le/la/les désignent; un/une/des introduisent ou comptent.",examples:[["J’achète un livre.","Compro un libro."],["Le livre est intéressant.","El libro es interesante."]],keywords:["le","la","un","une","des"]},
  {id:"a1-contractes",level:"A1",group:"Avoir et demander",title:"Articles contractés",objective:"Combiner à ou de avec les articles définis.",rule:"À + le = au, à + les = aux; de + le = du, de + les = des.",examples:[["Je vais au marché.","Voy al mercado."],["Je reviens des États-Unis.","Regreso de Estados Unidos."]],keywords:["au","aux","du","des"]},
  {id:"a1-partitifs",level:"A1",group:"Avoir et demander",title:"Articles partitifs",objective:"Parler d’une quantité non comptée, notamment pour les aliments.",rule:"Utilisez du, de la, de l’, des; après une négation, utilisez généralement de/d’.",examples:[["Je bois de l’eau.","Bebo agua."],["Je ne mange pas de viande.","No como carne."]],keywords:["du","de la","de l’","quantité"]},
  {id:"a1-negation",level:"A1",group:"Avoir et demander",title:"La négation",objective:"Nier une action ou une information au présent.",rule:"Ne se place avant le verbe et pas après; ne devient n’ devant une voyelle.",examples:[["Je ne travaille pas aujourd’hui.","No trabajo hoy."],["Elle n’a pas de voiture.","Ella no tiene automóvil."]],keywords:["ne…pas","n’…pas","jamais","plus"]},
  {id:"a1-questions",level:"A1",group:"Avoir et demander",title:"Poser des questions",objective:"Demander une personne, un lieu, un moment, une raison ou un choix.",rule:"Utilisez l’intonation, « est-ce que » ou l’inversion avec qui, où, quand, pourquoi, quel.",examples:[["Où est-ce que tu habites ?","¿Dónde vives?"],["Pourquoi apprenez-vous le français ?","¿Por qué aprende francés?"]],keywords:["qui","où","quand","pourquoi","quel"]},
  {id:"a1-er",level:"A1",group:"Actions quotidiennes",title:"Verbes en -ER au présent",objective:"Décrire des habitudes et des actions simples.",rule:"Terminaisons: -e, -es, -e, -ons, -ez, -ent.",examples:[["Nous parlons français.","Hablamos francés."],["Ils regardent un film.","Miran una película."]],keywords:["parler","habiter","travailler","présent"]},
  {id:"a1-cuisine",level:"A1",group:"Actions quotidiennes",title:"La cuisine",objective:"Comprendre une recette et parler des aliments et des gestes culinaires.",rule:"Les recettes emploient fréquemment l’infinitif ou l’impératif: couper, ajouter, mélanger, cuire.",examples:[["Coupez les légumes.","Corte las verduras."],["Ajoutez un peu de sel.","Agregue un poco de sal."]],keywords:["aliments","couper","mélanger","cuire"]},
  {id:"a2-pouvoir",level:"A2",group:"Modalité",title:"Pouvoir",objective:"Exprimer une capacité, une possibilité ou demander une permission.",rule:"Je peux, tu peux, il peut, nous pouvons, vous pouvez, ils peuvent.",examples:[["Pouvez-vous répéter ?","¿Puede repetir?"],["Nous pouvons vous aider.","Podemos ayudarle."]],keywords:["pouvoir","capacité","permission","demande"]},
  {id:"a2-vouloir",level:"A2",group:"Modalité",title:"Vouloir",objective:"Exprimer un souhait, une intention ou une demande polie.",rule:"Je veux… est direct; « je voudrais… » est plus poli dans un service.",examples:[["Je veux apprendre.","Quiero aprender."],["Je voudrais un café.","Quisiera un café."]],keywords:["vouloir","souhait","intention","politesse"]},
  {id:"a2-devoir",level:"A2",group:"Modalité",title:"Devoir",objective:"Exprimer une obligation, une nécessité ou un conseil fort.",rule:"Je dois, tu dois, il doit, nous devons, vous devez, ils doivent.",examples:[["Vous devez remplir ce formulaire.","Debe completar este formulario."],["Nous devons partir.","Debemos irnos."]],keywords:["devoir","obligation","nécessité","conseil"]},
  {id:"a2-information",level:"A2",group:"Modalité",title:"Obtenir des renseignements",objective:"Demander poliment une information dans un service public ou commercial.",rule:"Combinez une formule de politesse, une question précise et une demande de confirmation.",examples:[["Pourriez-vous m’indiquer le prix ?","¿Podría indicarme el precio?"],["J’aimerais savoir si…","Me gustaría saber si…"]],keywords:["renseignements","service","prix","horaire"]},
  {id:"a2-ir",level:"A2",group:"Verbes au présent",title:"Verbes en -IR",objective:"Conjuguer finir, choisir et réussir au présent.",rule:"Pour le modèle finir: -is, -is, -it, -issons, -issez, -issent.",examples:[["Nous choisissons le train.","Elegimos el tren."],["Elles finissent à cinq heures.","Terminan a las cinco."]],keywords:["finir","choisir","réussir","-issons"]},
  {id:"a2-oir",level:"A2",group:"Verbes au présent",title:"Verbes en -OIR",objective:"Utiliser plusieurs verbes fréquents aux formes irrégulières.",rule:"Les verbes en -oir n’ont pas un seul modèle: voir, recevoir et savoir doivent être mémorisés.",examples:[["Je vois la montagne.","Veo la montaña."],["Vous recevez un courriel.","Recibe un correo."]],keywords:["voir","savoir","recevoir","irrégulier"]},
  {id:"a2-dre",level:"A2",group:"Verbes au présent",title:"Verbes en -RE et -DRE",objective:"Conjuguer prendre, comprendre, attendre et répondre.",rule:"Les bases peuvent changer au pluriel: je prends, nous prenons; je comprends, nous comprenons.",examples:[["Je prends l’autobus.","Tomo el autobús."],["Vous comprenez la question.","Comprende la pregunta."]],keywords:["prendre","comprendre","attendre","répondre"]},
  {id:"a2-aller",level:"A2",group:"Projets et pronoms",title:"Le verbe aller",objective:"Parler d’un déplacement et introduire un projet proche.",rule:"Je vais, tu vas, il va, nous allons, vous allez, ils vont.",examples:[["Nous allons au centre-ville.","Vamos al centro."],["Où allez-vous ?","¿Adónde va?"]],keywords:["aller","destination","déplacement","présent"]},
  {id:"a2-futur",level:"A2",group:"Projets et pronoms",title:"Le futur proche",objective:"Exprimer une intention ou un événement prochain.",rule:"Conjuguez aller au présent, puis ajoutez l’infinitif.",examples:[["Je vais appeler Marie.","Voy a llamar a Marie."],["Ils vont déménager.","Van a mudarse."]],keywords:["aller + infinitif","projet","demain","bientôt"]},
  {id:"a2-cod",level:"A2",group:"Projets et pronoms",title:"Pronoms directs",objective:"Remplacer une personne ou une chose directement liée au verbe.",rule:"Le, la, l’ et les se placent avant le verbe conjugué.",examples:[["Je connais Paul. Je le connais.","Conozco a Paul. Lo conozco."],["Elle achète les billets. Elle les achète.","Compra los boletos. Los compra."]],keywords:["le","la","les","COD"]},
  {id:"a2-coi",level:"A2",group:"Projets et pronoms",title:"Pronoms indirects",objective:"Remplacer une personne introduite par à.",rule:"Lui remplace à lui/à elle; leur remplace à eux/à elles.",examples:[["Je parle à Marie. Je lui parle.","Hablo con Marie. Le hablo."],["Nous écrivons aux clients. Nous leur écrivons.","Escribimos a los clientes. Les escribimos."]],keywords:["lui","leur","COI","à quelqu’un"]},
  {id:"a2-temps",level:"A2",group:"Temps et comparaison",title:"Prépositions de temps",objective:"Exprimer le début, la durée prévue ou le temps nécessaire.",rule:"Depuis: action encore actuelle; pendant: durée achevée; pour: durée prévue; en: temps nécessaire.",examples:[["J’habite ici depuis deux ans.","Vivo aquí desde hace dos años."],["Je pars pour trois semaines.","Me voy por tres semanas."]],keywords:["depuis","pendant","pour","en"]},
  {id:"a2-comparatif",level:"A2",group:"Temps et comparaison",title:"Le comparatif",objective:"Comparer des qualités, des quantités ou des actions.",rule:"Plus… que, moins… que, aussi… que; pour les noms: plus/moins/autant de… que.",examples:[["Ce livre est plus intéressant que l’autre.","Este libro es más interesante que el otro."],["Elle travaille autant que moi.","Trabaja tanto como yo."]],keywords:["plus","moins","aussi","que"]},
  {id:"a2-superlatif",level:"A2",group:"Temps et comparaison",title:"Le superlatif",objective:"Exprimer le degré maximal ou minimal dans un groupe.",rule:"Utilisez le/la/les plus ou le/la/les moins, en accordant l’article.",examples:[["C’est la plus grande ville.","Es la ciudad más grande."],["Voici le quartier le moins bruyant.","Este es el barrio menos ruidoso."]],keywords:["le plus","la plus","le moins","groupe"]},
  {id:"a2-reflexifs",level:"A2",group:"Temps et comparaison",title:"Verbes pronominaux",objective:"Décrire la routine et les actions faites sur soi-même.",rule:"Me, te, se, nous, vous, se se placent avant le verbe.",examples:[["Je me lève à sept heures.","Me levanto a las siete."],["Nous nous préparons.","Nos preparamos."]],keywords:["se lever","s’habiller","se coucher","routine"]},
  {id:"a2-passe",level:"A2",group:"Passé composé",title:"Passé composé avec avoir",objective:"Raconter une action terminée dans le passé.",rule:"Sujet + avoir au présent + participe passé; -er devient -é, -ir devient souvent -i.",examples:[["J’ai terminé mon travail.","Terminé mi trabajo."],["Nous avons choisi un restaurant.","Elegimos un restaurante."]],keywords:["avoir","participe passé","hier","action terminée"]},
  {id:"a2-participes",level:"A2",group:"Passé composé",title:"Participes passés fréquents",objective:"Mémoriser les formes irrégulières nécessaires pour raconter.",rule:"Faire-fait, prendre-pris, voir-vu, avoir-eu, lire-lu, boire-bu.",examples:[["Elle a fait un gâteau.","Hizo un pastel."],["Ils ont pris le métro.","Tomaron el metro."]],keywords:["fait","pris","vu","eu","lu"]},
  {id:"a1-svo",level:"A1",group:"Fondations grammaticales",title:"Pronoms sujets et ordre SVO",objective:"Construire une phrase simple dans l’ordre naturel du français.",rule:"La structure de base est sujet + verbe + complément; le sujet est presque toujours exprimé.",examples:[["Marie prépare le repas.","Marie prepara la comida."],["Elle prépare le repas.","Ella prepara la comida."]],keywords:["je","tu","il","elle","SVO"]},
  {id:"a1-cest",level:"A1",group:"Fondations grammaticales",title:"C’est et qu’est-ce que c’est",objective:"Identifier et présenter une personne ou une chose.",rule:"« C’est » identifie au singulier; « ce sont » identifie au pluriel.",examples:[["Qu’est-ce que c’est ? C’est un livre.","¿Qué es? Es un libro."],["Ce sont mes amis.","Son mis amigos."]],keywords:["c’est","ce sont","identifier","présenter"]},
  {id:"a1-voyelles",level:"A1",group:"Prononciation",title:"Voyelles orales",objective:"Distinguer des voyelles proches dans des mots fréquents.",rule:"Écoutez la position des lèvres et la durée; répétez d’abord lentement, puis dans une phrase.",examples:[["tu / tout","u francesa / u"],["mot / mode","palabra / moda"]],keywords:["u/ou","é/è","o/ɔ","paires minimales"]},
  {id:"a1-nasales",level:"A1",group:"Prononciation",title:"Voyelles nasales",objective:"Reconnaître et produire les sons écrits an/en, on et in/ain.",rule:"L’air passe aussi par le nez et le n final n’est généralement pas prononcé séparément.",examples:[["vent / vin","viento / vino"],["bon pain","buen pan"]],keywords:["an","on","in","nasal"]},
  {id:"a1-liaison",level:"A1",group:"Prononciation",title:"Liaison et élision",objective:"Enchaîner naturellement les mots fréquents.",rule:"Devant une voyelle, certaines consonnes finales se lient; je devient j’, ne devient n’.",examples:[["Nous avons","nous-z-avons"],["J’ai un ami.","Tengo un amigo."]],keywords:["liaison","élision","enchaînement","voyelle"]},
  {id:"a1-famille",level:"A1",group:"Se présenter",title:"La famille",objective:"Présenter les membres d’une famille et leurs relations.",rule:"Combinez les noms de famille, les possessifs et être/avoir pour décrire.",examples:[["Ma sœur a deux enfants.","Mi hermana tiene dos hijos."],["Voici mes grands-parents.","Estos son mis abuelos."]],keywords:["parents","frère","sœur","grands-parents"]},
  {id:"a1-etre-questions",level:"A1",group:"Questions",title:"Être : négation et questions",objective:"Nier et interroger une identité ou un état.",rule:"Ne…pas encadre être; l’inversion donne « Es-tu… ? », « Êtes-vous… ? ».",examples:[["Je ne suis pas disponible.","No estoy disponible."],["Êtes-vous prêt ?","¿Está listo?"]],keywords:["ne suis pas","es-tu","est-il","êtes-vous"]},
  {id:"a1-avoir-expressions",level:"A1",group:"Avoir et demander",title:"Expressions avec avoir",objective:"Exprimer sensations, besoins et émotions avec avoir.",rule:"Le français utilise avoir là où l’espagnol peut utiliser tener ou estar.",examples:[["J’ai faim et j’ai soif.","Tengo hambre y sed."],["Elle a besoin d’aide.","Necesita ayuda."]],keywords:["faim","soif","besoin","envie","peur"]},
  {id:"a1-corps",level:"A1",group:"Avoir et demander",title:"Le corps et avoir mal",objective:"Nommer les parties du corps et expliquer une douleur.",rule:"Avoir mal à + article contracté: au dos, à la tête, aux pieds.",examples:[["J’ai mal au dos.","Me duele la espalda."],["Il a mal aux yeux.","Le duelen los ojos."]],keywords:["tête","dos","bras","jambes","avoir mal"]},
  {id:"a1-genre-noms",level:"A1",group:"Objets et maison",title:"Genre des noms",objective:"Mémoriser un nom avec son article et reconnaître quelques terminaisons utiles.",rule:"Apprenez toujours le nom avec le/la; -tion est souvent féminin et -ment souvent masculin.",examples:[["la nation","la nación"],["le bâtiment","el edificio"]],keywords:["le","la","terminaisons","nom"]},
  {id:"a1-quantites",level:"A1",group:"Objets et maison",title:"Quantités + de",objective:"Exprimer une mesure ou une quantité précise.",rule:"Après beaucoup, un peu, un kilo, une tasse ou une bouteille, utilisez de/d’.",examples:[["une bouteille d’eau","una botella de agua"],["beaucoup de légumes","muchas verduras"]],keywords:["kilo","bouteille","tasse","beaucoup de"]},
  {id:"a1-il-y-a",level:"A1",group:"Objets et maison",title:"Il y a",objective:"Décrire ce qui existe ou manque dans un lieu.",rule:"Il y a; il n’y a pas de; est-ce qu’il y a… ? ou y a-t-il… ?",examples:[["Il y a une cuisine.","Hay una cocina."],["Il n’y a pas de balcon.","No hay balcón."]],keywords:["il y a","pas de","maison","existence"]},
  {id:"a1-er-changements",level:"A1",group:"Actions quotidiennes",title:"Verbes -ER avec changement",objective:"Conjuguer manger, commencer, acheter et préférer sans appliquer aveuglément un seul modèle.",rule:"Certains verbes adaptent l’orthographe pour conserver le son ou changent de voyelle.",examples:[["Nous mangeons ensemble.","Comemos juntos."],["Je préfère le thé.","Prefiero el té."]],keywords:["mangeons","commençons","achète","préfère"]},
  {id:"a1-imperatif",level:"A1",group:"Actions quotidiennes",title:"L’impératif",objective:"Donner une instruction ou un conseil avec tu, nous ou vous.",rule:"Supprimez le sujet; à la forme négative, ne…pas entoure le verbe.",examples:[["Mélangez les ingrédients.","Mezcle los ingredientes."],["Ne mange pas trop vite !","¡No comas tan rápido!"]],keywords:["ordre","conseil","tu","nous","vous"]},
  {id:"a2-modal-formes",level:"A2",group:"Modalité",title:"Modaux : négation et interrogation",objective:"Transformer pouvoir, vouloir et devoir dans les trois formes.",rule:"Ne…pas entoure le modal; l’inversion place le pronom après le verbe.",examples:[["Je ne peux pas venir.","No puedo venir."],["Doit-on réserver ?","¿Hay que reservar?"]],keywords:["peut-on","voulez-vous","doit-on","ne…pas"]},
  {id:"a2-invitations",level:"A2",group:"Communication",title:"Inviter, accepter et refuser",objective:"Gérer une invitation avec le registre adapté et proposer une solution.",rule:"Acceptez clairement ou refusez avec excuse et contre-proposition.",examples:[["Avec plaisir !","¡Con gusto!"],["Je suis désolé, mais je suis occupé. Une autre fois ?","Lo siento, estoy ocupado. ¿Otro día?"]],keywords:["inviter","accepter","refuser","contre-proposition"]},
  {id:"a2-faire-dire",level:"A2",group:"Verbes au présent",title:"Faire et dire",objective:"Parler d’activités, de météo et rapporter une parole.",rule:"Je fais/nous faisons/ils font; je dis/nous disons/vous dites.",examples:[["Il fait froid.","Hace frío."],["Vous dites la vérité.","Dice la verdad."]],keywords:["faire","dire","météo","activité"]},
  {id:"a2-venir-tenir",level:"A2",group:"Verbes au présent",title:"Venir et tenir",objective:"Utiliser deux familles irrégulières fréquentes.",rule:"Je viens/nous venons/ils viennent; je tiens/nous tenons/ils tiennent.",examples:[["Elle vient demain.","Viene mañana."],["Nous tenons notre promesse.","Cumplimos nuestra promesa."]],keywords:["venir","tenir","viennent","tiennent"]},
  {id:"a2-temps-etendu",level:"A2",group:"Temps et comparaison",title:"Dans, il y a, dès et jusqu’à",objective:"Situer précisément une action dans le passé ou le futur.",rule:"Dans = futur; il y a = passé; dès = point de départ; jusqu’à = limite.",examples:[["Je pars dans deux jours.","Me voy dentro de dos días."],["Il est arrivé il y a une heure.","Llegó hace una hora."]],keywords:["dans","il y a","dès","jusqu’à"]},
  {id:"a2-pronom-y",level:"A2",group:"Projets et pronoms",title:"Le pronom y",objective:"Remplacer un lieu ou à + chose.",rule:"Y ne remplace généralement pas une personne et se place avant le verbe.",examples:[["Je vais au marché. J’y vais.","Voy al mercado. Voy allí."],["Je pense à mon projet. J’y pense.","Pienso en mi proyecto."]],keywords:["y","lieu","à + chose","pronom"]},
  {id:"a2-pronom-en",level:"A2",group:"Projets et pronoms",title:"Le pronom en",objective:"Remplacer de + chose ou une quantité.",rule:"Conservez la quantité après le verbe: j’en achète trois.",examples:[["Je parle de ce livre. J’en parle.","Hablo de este libro. Hablo de él."],["J’achète trois pommes. J’en achète trois.","Compro tres manzanas. Compro tres."]],keywords:["en","de + chose","quantité","pronom"]},
  {id:"a2-pronoms-ordre",level:"A2",group:"Projets et pronoms",title:"Ordre des pronoms",objective:"Combiner plusieurs pronoms sans hésiter.",rule:"Ordre utile: me/te/nous/vous, le/la/les, lui/leur, y, en.",examples:[["Je le lui donne.","Se lo doy."],["Nous y en achetons.","Compramos allí algunos."]],keywords:["ordre","le lui","y en","double pronom"]},
  {id:"a2-regime",level:"A2",group:"Projets et pronoms",title:"Verbes avec à, de ou sans préposition",objective:"Choisir la construction qui suit un verbe.",rule:"Commencer à, avoir besoin de, aimer + infinitif: apprenez la construction avec le verbe.",examples:[["Elle commence à travailler.","Empieza a trabajar."],["Nous avons besoin de partir.","Necesitamos irnos."]],keywords:["à","de","infinitif","construction"]},
  {id:"a2-reflexifs-formes",level:"A2",group:"Temps et comparaison",title:"Pronominaux : négation et questions",objective:"Nier et interroger une action pronominale.",rule:"Le pronom reste devant le verbe: je ne me lève pas; vous levez-vous ?",examples:[["Elle ne se couche pas tard.","No se acuesta tarde."],["Vous préparez-vous ?","¿Se prepara?"]],keywords:["ne se…pas","vous…-vous","routine","question"]},
  {id:"a2-passe-formes",level:"A2",group:"Passé composé",title:"Passé : négation et questions",objective:"Nier et interroger une action passée.",rule:"Ne…pas entoure l’auxiliaire; l’inversion concerne l’auxiliaire.",examples:[["Je n’ai pas travaillé.","No trabajé."],["Avez-vous compris ?","¿Comprendió?"]],keywords:["n’ai pas","avez-vous","auxiliaire","passé"]},
  {id:"a2-passe-etre",level:"A2",group:"Passé composé",title:"Passé composé avec être",objective:"Raconter les déplacements et accorder le participe avec le sujet.",rule:"Certains verbes de mouvement utilisent être; le participe s’accorde en genre et en nombre.",examples:[["Elle est arrivée hier.","Llegó ayer."],["Ils sont partis tôt.","Se fueron temprano."]],keywords:["être","arrivée","partis","accord"]},
  {id:"a2-vandertramp",level:"A2",group:"Passé composé",title:"Vandertramp : les verbes avec être",objective:"Mémoriser les verbes usuels de déplacement ou de changement d’état qui utilisent être au passé composé.",rule:"La mnemotecnia Vandertramp ayuda, pero no es una regla absoluta: aller, venir, arriver, partir, entrer, sortir, monter, descendre, naître, mourir, tomber, rester, retourner, passer y rentrer suelen usar être cuando describen movimiento o cambio. Los verbos pronominales también usan être. El participio concuerda: elle est arrivée, ils sont partis.",examples:[["Nous sommes arrivés à Montréal.","Llegamos a Montreal."],["Elle est sortie; elles se sont levées tôt.","Ella salió; ellas se levantaron temprano."]],keywords:["Vandertramp","être","accord","arrivé(e)(s)","verbes pronominaux"]},
  {id:"a2-passe-pronominal",level:"A2",group:"Passé composé",title:"Pronominaux au passé",objective:"Raconter une routine ou une action pronominale terminée.",rule:"Les verbes pronominaux utilisent être: je me suis levé(e).",examples:[["Elle s’est préparée.","Se preparó."],["Nous nous sommes couchés tard.","Nos acostamos tarde."]],keywords:["me suis","s’est","nous sommes","accord"]},
  {id:"a2-auxiliaire",level:"A2",group:"Passé composé",title:"Choisir avoir ou être",objective:"Sélectionner l’auxiliaire et corriger les erreurs fréquentes.",rule:"La plupart des verbes utilisent avoir; les pronominaux et certains déplacements utilisent être.",examples:[["J’ai pris le métro.","Tomé el metro."],["Je suis allé au bureau.","Fui a la oficina."]],keywords:["avoir","être","choix","transitif"]},
  {id:"a2-hier-demain",level:"A2",group:"Intégration",title:"Hier, aujourd’hui, demain",objective:"Relier passé composé, présent et futur proche dans un récit.",rule:"Choisissez le temps selon le repère temporel et maintenez une chronologie claire.",examples:[["Hier, j’ai travaillé; aujourd’hui, je me repose.","Ayer trabajé; hoy descanso."],["Demain, je vais sortir.","Mañana voy a salir."]],keywords:["hier","aujourd’hui","demain","chronologie"]},
  {id:"a2-prononciation",level:"A2",group:"Prononciation",title:"Formes qui se prononcent pareil",objective:"Distinguer par le contexte des formes verbales homophones.",rule:"Parle, parles et parlent se prononcent souvent pareil; l’écrit dépend du sujet.",examples:[["je peux / il peut","puedo / puede"],["aller / allé","ir / ido"]],keywords:["homophones","-ent muet","-é/-er","contexte"]},
  {id:"b1-imparfait",level:"B1",group:"Raconter au passé",title:"L’imparfait",objective:"Décrire une habitude, un décor, une émotion ou une action en cours dans le passé.",rule:"Prenez la forme nous au présent, retirez -ons et ajoutez -ais, -ais, -ait, -ions, -iez, -aient. Être est irrégulier : j’étais.",examples:[["Quand j’étais enfant, je jouais dehors.","Cuando era niño, jugaba afuera."],["Il pleuvait et la rue était vide.","Llovía y la calle estaba vacía."]],keywords:["habitude","description","contexte","était"]},
  {id:"b1-passe-imparfait",level:"B1",group:"Raconter au passé",title:"Passé composé ou imparfait",objective:"Distinguer le cadre ou l’action en cours del hecho puntual que avanza el relato.",rule:"L’imparfait crée le décor ou une action en cours; le passé composé marque un fait terminé, bref ou soudain.",examples:[["Je lisais quand le téléphone a sonné.","Leía cuando sonó el teléfono."],["Tous les étés, nous allions à la mer.","Todos los veranos íbamos al mar."]],keywords:["pendant que","soudain","cadre","événement"]},
  {id:"b1-pqp",level:"B1",group:"Raconter au passé",title:"Le plus-que-parfait",objective:"Exprimer une action terminée avant une autre action passée.",rule:"Imparfait de avoir ou être + participe passé : j’avais fini, elle était partie.",examples:[["Le film avait déjà commencé quand nous sommes arrivés.","La película ya había comenzado cuando llegamos."],["Elle était partie avant mon appel.","Ella se había ido antes de mi llamada."]],keywords:["avant","déjà","avait","était"]},
  {id:"b1-conditionnel",level:"B1",group:"Hypothèses et conseils",title:"Le conditionnel présent et passé",objective:"Formuler un souhait, un conseil, una hipótesis o un arrepentimiento.",rule:"Futur radical + terminaisons de l’imparfait : je pourrais. Avec si : si + imparfait, conditionnel; si + plus-que-parfait, conditionnel passé.",examples:[["Si j’avais plus de temps, je voyagerais.","Si tuviera más tiempo, viajaría."],["Si tu m’avais prévenu, je serais venu.","Si me hubieras avisado, habría venido."]],keywords:["si","pourrais","devrais","j’aurais"]},
  {id:"b1-subjonctif",level:"B1",group:"Opinion et nécessité",title:"Le subjonctif",objective:"Exprimer la nécessité, le doute, l’émotion, el deseo o una finalidad.",rule:"Après il faut que, je veux que, bien que, pour que… : que je fasse, que nous finissions. Mémorisez être, avoir, aller, faire, pouvoir, vouloir et venir.",examples:[["Il faut que nous partions à l’heure.","Es necesario que salgamos a tiempo."],["Je doute qu’elle soit disponible.","Dudo que ella esté disponible."]],keywords:["il faut que","bien que","pour que","soit"]},
  {id:"b1-argumentation",level:"B1",group:"TEF / TCF",title:"Convaincre et rédiger une opinion",objective:"Organiser una opinión clara con argumentos, contraste y conclusión.",rule:"Annoncez le sujet, développez une thèse et une antithèse, donnez votre position puis concluez. Utilisez d’abord, de plus, cependant, en revanche et en conclusion.",examples:[["À mon avis, le télétravail offre plus de flexibilité.","En mi opinión, el teletrabajo ofrece más flexibilidad."],["Cependant, il peut isoler certains employés.","Sin embargo, puede aislar a algunos empleados."]],keywords:["à mon avis","cependant","en revanche","conclusion"]},
];

export const courseExercises: CourseExercise[] = [
  {id:"e01",level:"A1",skill:"Vocabulaire",mode:"choice",prompt:"Quel mot correspond à « jueves » ?",answer:"jeudi",options:["mardi","jeudi","samedi"],hint:"Les jours de la semaine."},
  {id:"e02",level:"A1",skill:"Vocabulaire",mode:"fill",prompt:"Le mois après avril est ___.",answer:"mai",hint:"Les mois de l’année."},
  {id:"e03",level:"A1",skill:"Temps",mode:"choice",prompt:"80 s’écrit…",answer:"quatre-vingts",options:["soixante-dix","quatre-vingts","quatre-vingt-dix"],hint:"Quatre fois vingt; le s disparaît si un autre nombre suit."},
  {id:"e04",level:"A1",skill:"Communication",mode:"reorder",prompt:"Remettez la présentation en ordre.",answer:"Je m’appelle Sofia",tokens:["Sofia","m’appelle","Je"],hint:"Sujet + pronom + verbe + prénom."},
  {id:"e05",level:"A1",skill:"Verbes",mode:"fill",prompt:"Nous ___ étudiants. (être)",answer:"sommes",hint:"Être avec nous."},
  {id:"e06",level:"A1",skill:"Grammaire",mode:"transform",prompt:"Mettez au féminin : Il est sportif.",answer:"Elle est sportive",hint:"Sportif devient sportive."},
  {id:"e07",level:"A1",skill:"Communication",mode:"choice",prompt:"Quelle phrase est correcte pour une profession ?",answer:"Elle est médecin.",options:["Elle est une médecin.","Elle est médecin.","Elle a médecin."],hint:"Après être, la profession est généralement sans article."},
  {id:"e08",level:"A1",skill:"Grammaire",mode:"fill",prompt:"Je vais ___ Paul ce soir.",answer:"chez",hint:"Lieu associé à une personne."},
  {id:"e09",level:"A1",skill:"Temps",mode:"choice",prompt:"8 h 30 se dit…",answer:"huit heures et demie",options:["huit heures et quart","huit heures et demie","neuf heures moins le quart"],hint:"Trente minutes = et demie."},
  {id:"e10",level:"A1",skill:"Grammaire",mode:"fill",prompt:"C’est ___ sœur. (je)",answer:"ma",hint:"Sœur est féminin singulier."},
  {id:"e11",level:"A1",skill:"Verbes",mode:"fill",prompt:"Vous ___ une réservation. (avoir)",answer:"avez",hint:"Avoir avec vous."},
  {id:"e12",level:"A1",skill:"Grammaire",mode:"choice",prompt:"Je vois pour la première fois…",answer:"un chien",options:["le chien","un chien","du chien"],hint:"On présente un élément comptable non identifié."},
  {id:"e13",level:"A1",skill:"Grammaire",mode:"fill",prompt:"Nous allons ___ marché.",answer:"au",hint:"À + le = au."},
  {id:"e14",level:"A1",skill:"Grammaire",mode:"fill",prompt:"Je bois ___ eau.",answer:"de l’",hint:"Partitif devant une voyelle."},
  {id:"e15",level:"A1",skill:"Grammaire",mode:"transform",prompt:"Mettez à la négation : J’ai une voiture.",answer:"Je n’ai pas de voiture",hint:"Après pas, l’article indéfini devient de."},
  {id:"e16",level:"A1",skill:"Communication",mode:"reorder",prompt:"Construisez une question sur le lieu.",answer:"Où est-ce que tu habites",tokens:["tu","habites","Où","est-ce","que"],hint:"Mot interrogatif + est-ce que + sujet + verbe."},
  {id:"e17",level:"A1",skill:"Verbes",mode:"fill",prompt:"Ils ___ français chaque jour. (parler)",answer:"parlent",hint:"La terminaison -ent ne se prononce pas."},
  {id:"e18",level:"A1",skill:"Verbes",mode:"transform",prompt:"Conjuguez avec nous : Je regarde la télévision.",answer:"Nous regardons la télévision",hint:"Nous + verbe en -ons."},
  {id:"e19",level:"A1",skill:"Vocabulaire",mode:"choice",prompt:"Quel verbe signifie « cortar » ?",answer:"couper",options:["cuire","couper","mélanger"],hint:"Un geste de cuisine."},
  {id:"e20",level:"A1",skill:"Communication",mode:"reorder",prompt:"Donnez une instruction de cuisine.",answer:"Ajoutez un peu de sel",tokens:["de","sel","Ajoutez","un","peu"],hint:"Impératif + complément."},
  {id:"e21",level:"A1",skill:"Vocabulaire",mode:"fill",prompt:"La saison après l’hiver est ___.",answer:"le printemps",hint:"Mars, avril et mai."},
  {id:"e22",level:"A1",skill:"Communication",mode:"choice",prompt:"Formule formelle pour prendre congé :",answer:"Au revoir, bonne journée.",options:["Salut !","Au revoir, bonne journée.","Coucou !"],hint:"Choisissez une formule adaptée à vous."},
  {id:"e23",level:"A1",skill:"Grammaire",mode:"transform",prompt:"Mettez au pluriel : C’est son livre.",answer:"Ce sont ses livres",hint:"Son devient ses; c’est devient ce sont."},
  {id:"e24",level:"A1",skill:"Temps",mode:"fill",prompt:"La réunion commence ___ neuf heures.",answer:"à",hint:"À + heure précise."},
  {id:"e25",level:"A2",skill:"Verbes",mode:"fill",prompt:"Nous ___ vous aider. (pouvoir)",answer:"pouvons",hint:"Pouvoir avec nous."},
  {id:"e26",level:"A2",skill:"Communication",mode:"choice",prompt:"Demande la plus polie au café :",answer:"Je voudrais un café, s’il vous plaît.",options:["Je veux un café.","Je voudrais un café, s’il vous plaît.","Donnez-moi café."],hint:"Le conditionnel de politesse adoucit la demande."},
  {id:"e27",level:"A2",skill:"Verbes",mode:"fill",prompt:"Vous ___ présenter une pièce d’identité. (devoir)",answer:"devez",hint:"Devoir avec vous."},
  {id:"e28",level:"A2",skill:"Communication",mode:"reorder",prompt:"Demandez un renseignement poliment.",answer:"Pourriez-vous m’indiquer le prix",tokens:["le","m’indiquer","Pourriez-vous","prix"],hint:"Conditionnel + pronom + infinitif."},
  {id:"e29",level:"A2",skill:"Verbes",mode:"fill",prompt:"Elles ___ leur travail. (finir)",answer:"finissent",hint:"Finir avec elles: -issent."},
  {id:"e30",level:"A2",skill:"Verbes",mode:"fill",prompt:"Nous ___ le train. (choisir)",answer:"choisissons",hint:"Choisir avec nous: -issons."},
  {id:"e31",level:"A2",skill:"Verbes",mode:"fill",prompt:"Je ___ la montagne. (voir)",answer:"vois",hint:"Voir: je vois."},
  {id:"e32",level:"A2",skill:"Verbes",mode:"fill",prompt:"Vous ___ la réponse. (savoir)",answer:"savez",hint:"Savoir avec vous."},
  {id:"e33",level:"A2",skill:"Verbes",mode:"fill",prompt:"Ils ___ l’autobus. (prendre)",answer:"prennent",hint:"Deux n au pluriel ils/elles."},
  {id:"e34",level:"A2",skill:"Grammaire",mode:"transform",prompt:"Mettez à la négation : Elle comprend la question.",answer:"Elle ne comprend pas la question",hint:"Ne… pas encadre le verbe."},
  {id:"e35",level:"A2",skill:"Verbes",mode:"fill",prompt:"Nous ___ au musée. (aller)",answer:"allons",hint:"Aller avec nous."},
  {id:"e36",level:"A2",skill:"Temps",mode:"reorder",prompt:"Exprimez un projet proche.",answer:"Je vais chercher un appartement",tokens:["un","vais","Je","appartement","chercher"],hint:"Aller au présent + infinitif."},
  {id:"e37",level:"A2",skill:"Grammaire",mode:"transform",prompt:"Remplacez « le film » : Je regarde le film.",answer:"Je le regarde",hint:"Le pronom direct se place avant le verbe."},
  {id:"e38",level:"A2",skill:"Grammaire",mode:"transform",prompt:"Remplacez « à Marie » : Je téléphone à Marie.",answer:"Je lui téléphone",hint:"À une personne = lui."},
  {id:"e39",level:"A2",skill:"Temps",mode:"fill",prompt:"J’habite au Canada ___ 2023.",answer:"depuis",hint:"L’action continue aujourd’hui."},
  {id:"e40",level:"A2",skill:"Temps",mode:"choice",prompt:"Je suis parti ___ deux semaines, puis je suis revenu.",answer:"pendant",options:["depuis","pendant","en"],hint:"Durée achevée."},
  {id:"e41",level:"A2",skill:"Grammaire",mode:"fill",prompt:"Ce trajet est ___ rapide que l’autre.",answer:"plus",hint:"Comparatif de supériorité."},
  {id:"e42",level:"A2",skill:"Grammaire",mode:"transform",prompt:"Exprimez le maximum : Cette ville est grande dans la région.",answer:"C’est la plus grande ville de la région",hint:"La + plus + adjectif féminin."},
  {id:"e43",level:"A2",skill:"Verbes",mode:"fill",prompt:"Je me ___ à sept heures. (lever)",answer:"lève",hint:"Le e devient è devant une syllabe muette."},
  {id:"e44",level:"A2",skill:"Verbes",mode:"transform",prompt:"Mettez au passé composé : Nous terminons le projet.",answer:"Nous avons terminé le projet",hint:"Avoir au présent + terminé."},
  {id:"e45",level:"A2",skill:"Verbes",mode:"fill",prompt:"Elle a ___ un gâteau. (faire)",answer:"fait",hint:"Participe passé irrégulier."},
  {id:"e46",level:"A2",skill:"Verbes",mode:"fill",prompt:"Ils ont ___ le métro. (prendre)",answer:"pris",hint:"Participe passé de prendre."},
  {id:"e47",level:"A2",skill:"Communication",mode:"choice",prompt:"Pour demander une confirmation :",answer:"Est-ce que le prix comprend les taxes ?",options:["Le prix taxes.","Est-ce que le prix comprend les taxes ?","Pourquoi prix ?"],hint:"Question complète et précise."},
  {id:"e48",level:"A2",skill:"Grammaire",mode:"transform",prompt:"Remplacez « les clients » : Nous écrivons aux clients.",answer:"Nous leur écrivons",hint:"À plusieurs personnes = leur."},
  {id:"e49",level:"A2",skill:"Temps",mode:"fill",prompt:"Je vais au Québec ___ trois mois. (durée prévue)",answer:"pour",hint:"Pour + durée prévue."},
  {id:"e50",level:"A2",skill:"Grammaire",mode:"choice",prompt:"Comparaison d’égalité correcte :",answer:"Elle est aussi patiente que lui.",options:["Elle est autant patiente que lui.","Elle est aussi patiente que lui.","Elle est si patiente de lui."],hint:"Aussi + adjectif + que."},
  {id:"e51",level:"A2",skill:"Verbes",mode:"fill",prompt:"Marie ___ à la gare à huit heures. (arriver)",answer:"est arrivée",hint:"Arriver se construit avec être; ajoute -e pour elle."},
  {id:"e52",level:"A2",skill:"Verbes",mode:"fill",prompt:"Nous ___ tôt ce matin. (partir)",answer:"sommes partis",hint:"Partir utilise être; -s marque nous au masculin o grupo mixto."},
  {id:"e53",level:"A2",skill:"Grammaire",mode:"choice",prompt:"Choisissez la phrase correcte :",answer:"Elles sont descendues du bus.",options:["Elles ont descendues du bus.","Elles sont descendues du bus.","Elles sont descendu du bus."],hint:"Descendre de un lugar usa être; elles exige -es."},
  {id:"e54",level:"A2",skill:"Verbes",mode:"transform",prompt:"Mettez au passé composé : Elle entre dans la maison.",answer:"Elle est entrée dans la maison",hint:"Entrer describe movimiento hacia un lugar: être + participio concordado."},
  {id:"e55",level:"A2",skill:"Verbes",mode:"fill",prompt:"Ils se ___ à six heures. (lever)",answer:"sont levés",hint:"Todo verbo pronominal usa être en passé composé."},
  {id:"e56",level:"A2",skill:"Grammaire",mode:"choice",prompt:"Quelle phrase est correcte pour une action transitiva ?",answer:"J’ai sorti les livres du sac.",options:["Je suis sorti les livres du sac.","J’ai sorti les livres du sac.","Je suis sortie les livres du sac."],hint:"Sortir + objeto directo usa avoir; sin objeto, Je suis sorti(e)."},
  {id:"b1-01",level:"B1",skill:"Verbes",mode:"fill",prompt:"Quand j’étais enfant, je ___ dehors. (jouer)",answer:"jouais",hint:"Habitude au passé : imparfait avec je."},
  {id:"b1-02",level:"B1",skill:"Temps",mode:"choice",prompt:"Choisissez le bon temps : Pendant que nous ___, la lumière s’est éteinte.",answer:"dînions",options:["avons dîné","dînions","avions dîné"],hint:"Action en cours = imparfait."},
  {id:"b1-03",level:"B1",skill:"Temps",mode:"fill",prompt:"Il ___ froid et soudain la neige ___. (faire / commencer)",answer:"faisait / a commencé",hint:"Décor : imparfait; événement soudain : passé composé."},
  {id:"b1-04",level:"B1",skill:"Grammaire",mode:"transform",prompt:"Réunissez les phrases : Nous sommes arrivés. Le film avait commencé.",answer:"Quand nous sommes arrivés, le film avait commencé",hint:"L’action antérieure utilise le plus-que-parfait."},
  {id:"b1-05",level:"B1",skill:"Verbes",mode:"fill",prompt:"Elle ne pouvait pas entrer parce qu’elle ___ ses clés. (perdre)",answer:"avait perdu",hint:"Perte antérieure à l’impossibilité passée."},
  {id:"b1-06",level:"B1",skill:"Temps",mode:"choice",prompt:"Quelle phrase exprime une action antérieure ?",answer:"Ils étaient partis avant notre arrivée.",options:["Ils partaient avant notre arrivée.","Ils sont partis avant notre arrivée.","Ils étaient partis avant notre arrivée."],hint:"Être à l’imparfait + participe passé."},
  {id:"b1-07",level:"B1",skill:"Communication",mode:"reorder",prompt:"Formulez une hypothèse réaliste.",answer:"Si j’avais plus de temps je voyagerais",tokens:["voyagerais","Si","plus","j’avais","temps","de","je"],hint:"Si + imparfait, conditionnel présent."},
  {id:"b1-08",level:"B1",skill:"Verbes",mode:"fill",prompt:"Si tu m’avais prévenu, je ___ venu. (être)",answer:"serais",hint:"Conditionnel passé avec être."},
  {id:"b1-09",level:"B1",skill:"Grammaire",mode:"transform",prompt:"Donnez un conseil poli : Tu dois essayer cette activité.",answer:"Tu devrais essayer cette activité",hint:"Devoir au conditionnel = conseil."},
  {id:"b1-10",level:"B1",skill:"Communication",mode:"choice",prompt:"Quelle formule aide à convaincre ?",answer:"Tu pourrais essayer, c’est une belle occasion.",options:["Tu fais ça maintenant.","Tu pourrais essayer, c’est une belle occasion.","Tu as faire ça."],hint:"Pourrais adoucit la proposition."},
  {id:"b1-11",level:"B1",skill:"Verbes",mode:"fill",prompt:"Il faut que nous ___ à l’heure. (partir)",answer:"partions",hint:"Subjonctif de partir avec nous."},
  {id:"b1-12",level:"B1",skill:"Verbes",mode:"fill",prompt:"Je doute qu’il ___ la réponse. (avoir)",answer:"ait",hint:"Avoir au subjonctif : qu’il ait."},
  {id:"b1-13",level:"B1",skill:"Grammaire",mode:"choice",prompt:"Après « bien que », choisissez :",answer:"Bien qu’il fasse froid, nous sortons.",options:["Bien qu’il fait froid, nous sortons.","Bien qu’il fasse froid, nous sortons.","Bien qu’il fera froid, nous sortons."],hint:"Bien que demande le subjonctif."},
  {id:"b1-14",level:"B1",skill:"Grammaire",mode:"transform",prompt:"Transformez avec « pour que » : Je répète. Tu comprends.",answer:"Je répète pour que tu comprennes",hint:"Pour que + subjonctif."},
  {id:"b1-15",level:"B1",skill:"Communication",mode:"reorder",prompt:"Construisez une opinion nuancée.",answer:"À mon avis ce projet est utile cependant il coûte cher",tokens:["ce","cependant","projet","À","cher","il","avis","est","mon","utile","coûte"],hint:"Opinion + argument + contraste."},
  {id:"b1-16",level:"B1",skill:"Communication",mode:"choice",prompt:"Quel connecteur introduit une opposition ?",answer:"En revanche",options:["Tout d’abord","En revanche","En conclusion"],hint:"Il oppose une idée à la précédente."},
  {id:"b1-17",level:"B1",skill:"Communication",mode:"fill",prompt:"Pour terminer un texte argumentatif, utilisez : ___, cette solution paraît équilibrée.",answer:"En conclusion",hint:"Connecteur de clôture."},
  {id:"b1-18",level:"B1",skill:"Temps",mode:"fill",prompt:"Quand nous étions petits, nous ___ chez nos grands-parents chaque été. (aller)",answer:"allions",hint:"Aller à l’imparfait avec nous."},
];

export const tcfPromptBank: Record<TcfTaskId,string[]> = {
  tache1:[
    "Invitez vos amis à une fête de fin d’examens; précisez date, lieu, thème et programme.","Proposez un pique-nique et indiquez ce que chacun doit apporter.","Félicitez une amie pour son mariage et proposez votre aide.","Invitez une amie à un concert et donnez les informations pratiques.","Organisez une soirée cinéma et présentez le film choisi.","Proposez un repas familial pour un anniversaire.","Invitez des amis à une exposition temporaire.","Proposez de participer à un festival de musique.","Organisez une randonnée à vélo avec un groupe.","Proposez un programme pour célébrer le Nouvel An.","Conseillez un ami qui veut commencer le yoga.","Recommandez un coiffeur et expliquez pourquoi.","Aidez une amie à choisir un ordinateur portable.","Conseillez un débutant qui veut apprendre à cuisiner.","Recommandez un lieu calme pour étudier.","Donnez des conseils avant d’adopter un animal.","Proposez des méthodes pour améliorer son français.","Suggérez trois activités pour le week-end.","Recommandez une association pour faire du bénévolat.","Proposez une idée de cadeau original.","Rédigez une annonce pour vendre des meubles.","Signalez un problème de sécurité dans votre immeuble.","Rédigez une annonce pour chercher un colocataire.","Écrivez poliment à un voisin au sujet du bruit.","Organisez une fête des voisins.","Demandez des conseils pour un voyage en France.","Racontez brièvement un séjour et recommandez la destination.","Préparez un programme pour la visite d’un ami.","Recommandez un restaurant récemment découvert.","Proposez un voyage en voiture avec des amis.","Donnez des conseils pour un échange linguistique.","Présentez un musée qui mérite une visite.","Expliquez quelques aspects de la culture québécoise.","Racontez un spectacle de danse traditionnelle à une amie.","Conseillez une personne qui prépare un voyage humanitaire.","Annoncez la réussite d’un examen et racontez vos efforts.","Présentez une occasion de stage intéressante.","Racontez une conférence sur l’intelligence artificielle.","Donnez des conseils pour préparer un entretien d’embauche.","Recommandez une série récemment découverte.","Rédigez une annonce pour chercher un vélo d’occasion.","Recommandez un jeu vidéo et expliquez son intérêt.","Invitez à une action de nettoyage écologique.","Partagez des gestes simples pour économiser l’énergie."
  ],
  tache2:[
    "Racontez une randonnée guidée dans un parc canadien.","Présentez un cours de danse découvert récemment.","Racontez un week-end sans technologie.","Donnez votre avis sur un film indépendant vu dans un cinéma local.","Présentez un nouveau marché biologique.","Racontez un atelier consacré à la gestion du stress.","Partagez une expérience dans un atelier de peinture.","Racontez une journée sportive organisée par votre établissement.","Présentez une découverte culinaire faite avec un ami étranger.","Racontez un atelier de fabrication de fromage.","Décrivez une exposition de photographies historiques.","Expliquez les effets de repas familiaux sans téléphone.","Racontez un cours de yoga en plein air.","Présentez un atelier de cosmétiques naturels.","Racontez un festival de cinéma international.","Expliquez pourquoi vous avez adopté le vélo.","Partagez une expérience dans une banque alimentaire.","Racontez votre première expérience de paddle.","Présentez un atelier de jardinage urbain.","Décrivez une visite dans un musée d’art moderne.","Présentez un café littéraire de votre quartier.","Partagez les idées d’une conférence sur l’entrepreneuriat.","Racontez une séance de méditation en forêt.","Expliquez comment vous avez réduit votre consommation de plastique.","Présentez un nouveau centre culturel.","Racontez une soirée de dégustation de thé.","Présentez une application de coaching sportif testée récemment.","Racontez une visite dans un parc consacré à la biodiversité.","Donnez votre avis sur un spectacle d’humour amateur.","Racontez une semaine sans télévision ni plateformes vidéo.","Présentez un atelier de poterie.","Racontez la découverte d’un restaurant de cuisine fusion.","Présentez une initiation à la permaculture.","Expliquez le fonctionnement d’une bibliothèque d’outils.","Racontez un atelier de réparation d’objets."
  ],
  tache3:[
    "La présence d’un animal domestique dans une famille.","Les devoirs scolaires après la classe.","La micro-sieste en entreprise.","Les jeux vidéo dans le quotidien des enfants.","Les achats en ligne.","La vie en colocation.","L’enseignement à domicile.","Le cadre de vie à la campagne.","Les échanges de services entre voisins.","Les activités artistiques après l’école.","Les espaces verts en ville.","L’alimentation biologique au quotidien.","Les événements culturels locaux.","Les plateformes de streaming.","Le télétravail.","Les cours de langues en ligne.","Les vélos en libre-service.","Les ateliers de cuisine pour adultes.","Les potagers urbains partagés.","Le bénévolat au sein d’associations.","Les formations professionnelles courtes.","Le covoiturage domicile-travail.","Les restaurants à thème.","Les brocantes et vide-greniers.","Les repas végétariens à la cantine.","Les bibliothèques municipales.","Les animations sportives de quartier.","Les stages d’été pour adolescents.","La réduction de l’usage des réseaux sociaux.","Les ateliers de recyclage et de réparation.","Les vacances solidaires.","Les maisons d’hôtes.","L’accueil d’étudiants étrangers.","Les concours artistiques amateurs.","Les programmes d’échanges internationaux."
  ]
};

export const tcfDrills: TcfDrill[] = [
  {task:"tache1",prompt:"Quelle ouverture convient à un message adressé à un ami ?",answer:"Salut Léa, j’espère que tu vas bien.",options:["Madame, Monsieur,","Salut Léa, j’espère que tu vas bien.","En conclusion,"],note:"Adaptez toujours le registre au destinataire."},
  {task:"tache1",prompt:"Après les détails d’une invitation, que faut-il ajouter ?",answer:"Une invitation à répondre",options:["Une nouvelle introduction","Une invitation à répondre","Une opinion contraire"],note:"Terminez l’échange: « Dis-moi si tu es disponible. »"},
  {task:"tache1",prompt:"Quel élément est indispensable dans un courriel ?",answer:"Un objet clair",options:["Un titre littéraire","Un objet clair","Deux arguments opposés"],note:"L’objet annonce immédiatement le but du message."},
  {task:"tache2",prompt:"Quel ordre organise le mieux un récit ?",answer:"Contexte, étapes, moment marquant, bilan",options:["Bilan, titre, contexte","Contexte, étapes, moment marquant, bilan","Opinion, synthèse, salutation"],note:"Le lecteur doit suivre l’expérience sans revenir en arrière."},
  {task:"tache2",prompt:"Quel connecteur introduit naturellement la deuxième étape ?",answer:"Ensuite",options:["Cependant","Ensuite","En somme"],note:"Utilisez des connecteurs chronologiques variés."},
  {task:"tache2",prompt:"Quelle conclusion est la plus adaptée ?",answer:"Je recommande vivement cette activité.",options:["Bonjour à tous,","D’un côté…","Je recommande vivement cette activité."],note:"La conclusion résume l’impression et ouvre sur une recommandation."},
  {task:"tache3",prompt:"Dans la synthèse, pouvez-vous donner votre opinion ?",answer:"Non, elle doit rester neutre.",options:["Oui, dès la première phrase.","Non, elle doit rester neutre.","Seulement avec « je pense »."],note:"L’opinion personnelle appartient à la deuxième partie."},
  {task:"tache3",prompt:"Quel connecteur oppose les deux documents ?",answer:"En revanche",options:["Tout d’abord","En revanche","Par exemple"],note:"Reliez les perspectives au lieu de faire deux résumés isolés."},
  {task:"tache3",prompt:"Quelle répartition respecte la consigne ?",answer:"40-60 mots de synthèse et 80-120 mots d’opinion",options:["100 mots de synthèse seulement","40-60 mots de synthèse et 80-120 mots d’opinion","60 mots au total"],note:"La longueur totale attendue est de 120 à 180 mots."},
];
