export type Level = "A1" | "A2" | "B1";
export type Lesson = {
  id: string;
  level: Level;
  group: string;
  title: string;
  objective: string;
  rule: string;
  examples: [string, string][];
  keywords: string[];
};

export type CourseExercise = {
  id: string;
  level: Level;
  skill: "Vocabulaire" | "Grammaire" | "Verbes" | "Communication" | "Temps";
  mode: "choice" | "fill" | "reorder" | "transform";
  prompt: string;
  answer: string;
  options?: string[];
  tokens?: string[];
  hint: string;
};

export type TcfTaskId = "tache1" | "tache2" | "tache3";
export type TcfDrill = { task: TcfTaskId; prompt: string; answer: string; options: string[]; note: string };

export const lessons: Lesson[] = [
  {id:"a1-alphabet",level:"A1",group:"Premiers repÃ¨res",title:"Alphabet et sons",objective:"Ã‰peler un nom et reconnaÃ®tre les principaux sons franÃ§ais.",rule:"En franÃ§ais, le nom des lettres et certains sons nasaux demandent une Ã©coute attentive.",examples:[["Comment Ã§a sâ€™Ã©crit ?","Â¿CÃ³mo se escribe?"],["Ã‡a sâ€™Ã©crit M-A-R-I-E.","Se escribe M-A-R-I-E."]],keywords:["alphabet","Ã©peler","accents","sons nasaux"]},
  {id:"a1-nombres",level:"A1",group:"Premiers repÃ¨res",title:"Nombres et quantitÃ©s",objective:"Comprendre et produire les nombres utiles au quotidien.",rule:"MÃ©morisez les blocs 0-20, les dizaines, puis les constructions particuliÃ¨res 70, 80 et 90.",examples:[["Jâ€™ai trente-deux ans.","Tengo 32 aÃ±os."],["Ã‡a coÃ»te quatre-vingt-dix dollars.","Cuesta 90 dÃ³lares."]],keywords:["0-100","prix","tÃ©lÃ©phone","Ã¢ge"]},
  {id:"a1-calendrier",level:"A1",group:"Premiers repÃ¨res",title:"Jours, mois et saisons",objective:"Donner une date et situer un Ã©vÃ©nement dans lâ€™annÃ©e.",rule:"Les jours et les mois sâ€™Ã©crivent normalement sans majuscule en franÃ§ais.",examples:[["Nous sommes lundi 12 mai.","Es lunes 12 de mayo."],["Mon anniversaire est en hiver.","Mi cumpleaÃ±os es en invierno."]],keywords:["semaine","mois","date","saisons"]},
  {id:"a1-saluer",level:"A1",group:"Se prÃ©senter",title:"Saluer et prendre congÃ©",objective:"Choisir une formule adaptÃ©e Ã  une situation formelle ou familiÃ¨re.",rule:"Utilisez Â« tu Â» avec les proches et Â« vous Â» dans une situation formelle.",examples:[["Bonjour, comment allez-vous ?","Buenos dÃ­as, Â¿cÃ³mo estÃ¡?"],["Salut, Ã  bientÃ´t !","Hola, Â¡hasta pronto!"]],keywords:["bonjour","salut","au revoir","vous"]},
  {id:"a1-etre",level:"A1",group:"Se prÃ©senter",title:"Le verbe Ãªtre",objective:"PrÃ©senter son identitÃ©, sa situation et une caractÃ©ristique.",rule:"Je suis, tu es, il/elle est, nous sommes, vous Ãªtes, ils/elles sont.",examples:[["Je suis argentine.","Soy argentina."],["Nous sommes Ã©tudiants.","Somos estudiantes."]],keywords:["Ãªtre","identitÃ©","Ã©tat","prÃ©sent"]},
  {id:"a1-genre",level:"A1",group:"Se prÃ©senter",title:"Masculin et fÃ©minin",objective:"Accorder les adjectifs avec la personne dÃ©crite.",rule:"On ajoute souvent -e au fÃ©minin, mais plusieurs formes sont irrÃ©guliÃ¨res.",examples:[["Il est sportif.","Ã‰l es deportista."],["Elle est sportive.","Ella es deportista."]],keywords:["adjectifs","accord","masculin","fÃ©minin"]},
  {id:"a1-identite",level:"A1",group:"Se prÃ©senter",title:"NationalitÃ©, profession et statut",objective:"DÃ©crire les informations essentielles dâ€™une personne.",rule:"AprÃ¨s Â« Ãªtre Â», la profession sâ€™utilise gÃ©nÃ©ralement sans article.",examples:[["Elle est mÃ©decin.","Ella es mÃ©dica."],["Il est canadien et cÃ©libataire.","Ã‰l es canadiense y soltero."]],keywords:["nationalitÃ©","profession","mariÃ©","cÃ©libataire"]},
  {id:"a1-prepositions",level:"A1",group:"Se prÃ©senter",title:"Ã€, de et chez",objective:"Indiquer un lieu, une origine ou la maison dâ€™une personne.",rule:"Ã€ indique souvent la destination; de, lâ€™origine; chez, le lieu associÃ© Ã  une personne.",examples:[["Je vais Ã  MontrÃ©al.","Voy a Montreal."],["Je dÃ®ne chez Paul.","Ceno en casa de Paul."]],keywords:["Ã ","de","chez","lieux"]},
  {id:"a1-heure",level:"A1",group:"Se prÃ©senter",title:"Dire lâ€™heure",objective:"Demander et indiquer lâ€™heure avec prÃ©cision.",rule:"On dit Â« Il estâ€¦ heure(s) Â», avec et quart, et demie ou moins le quart.",examples:[["Il est huit heures et demie.","Son las ocho y media."],["Ã€ quelle heure commence le cours ?","Â¿A quÃ© hora empieza el curso?"]],keywords:["heure","quart","demie","horaire"]},
  {id:"a1-possessifs",level:"A1",group:"Se prÃ©senter",title:"Les possessifs",objective:"Exprimer lâ€™appartenance en accordant avec lâ€™objet possÃ©dÃ©.",rule:"Mon/ma/mes, ton/ta/tes, son/sa/ses sâ€™accordent avec le nom qui suit.",examples:[["Câ€™est mon livre.","Es mi libro."],["Voici leurs enfants.","AquÃ­ estÃ¡n sus hijos."]],keywords:["mon","ma","mes","appartenance"]},
  {id:"a1-avoir",level:"A1",group:"Avoir et demander",title:"Le verbe avoir",objective:"Parler de possession, dâ€™Ã¢ge et de besoins courants.",rule:"Jâ€™ai, tu as, il/elle a, nous avons, vous avez, ils/elles ont.",examples:[["Jâ€™ai une voiture.","Tengo un automÃ³vil."],["Nous avons faim.","Tenemos hambre."]],keywords:["avoir","Ã¢ge","faim","soif"]},
  {id:"a1-articles",level:"A1",group:"Avoir et demander",title:"Articles dÃ©finis et indÃ©finis",objective:"Choisir entre un Ã©lÃ©ment identifiÃ© et un Ã©lÃ©ment prÃ©sentÃ© pour la premiÃ¨re fois.",rule:"Le/la/les dÃ©signent; un/une/des introduisent ou comptent.",examples:[["Jâ€™achÃ¨te un livre.","Compro un libro."],["Le livre est intÃ©ressant.","El libro es interesante."]],keywords:["le","la","un","une","des"]},
  {id:"a1-contractes",level:"A1",group:"Avoir et demander",title:"Articles contractÃ©s",objective:"Combiner Ã  ou de avec les articles dÃ©finis.",rule:"Ã€ + le = au, Ã  + les = aux; de + le = du, de + les = des.",examples:[["Je vais au marchÃ©.","Voy al mercado."],["Je reviens des Ã‰tats-Unis.","Regreso de Estados Unidos."]],keywords:["au","aux","du","des"]},
  {id:"a1-partitifs",level:"A1",group:"Avoir et demander",title:"Articles partitifs",objective:"Parler dâ€™une quantitÃ© non comptÃ©e, notamment pour les aliments.",rule:"Utilisez du, de la, de lâ€™, des; aprÃ¨s une nÃ©gation, utilisez gÃ©nÃ©ralement de/dâ€™.",examples:[["Je bois de lâ€™eau.","Bebo agua."],["Je ne mange pas de viande.","No como carne."]],keywords:["du","de la","de lâ€™","quantitÃ©"]},
  {id:"a1-negation",level:"A1",group:"Avoir et demander",title:"La nÃ©gation",objective:"Nier une action ou une information au prÃ©sent.",rule:"Ne se place avant le verbe et pas aprÃ¨s; ne devient nâ€™ devant une voyelle.",examples:[["Je ne travaille pas aujourdâ€™hui.","No trabajo hoy."],["Elle nâ€™a pas de voiture.","Ella no tiene automÃ³vil."]],keywords:["neâ€¦pas","nâ€™â€¦pas","jamais","plus"]},
  {id:"a1-questions",level:"A1",group:"Avoir et demander",title:"Poser des questions",objective:"Demander une personne, un lieu, un moment, une raison ou un choix.",rule:"Utilisez lâ€™intonation, Â« est-ce que Â» ou lâ€™inversion avec qui, oÃ¹, quand, pourquoi, quel.",examples:[["OÃ¹ est-ce que tu habites ?","Â¿DÃ³nde vives?"],["Pourquoi apprenez-vous le franÃ§ais ?","Â¿Por quÃ© aprende francÃ©s?"]],keywords:["qui","oÃ¹","quand","pourquoi","quel"]},
  {id:"a1-er",level:"A1",group:"Actions quotidiennes",title:"Verbes en -ER au prÃ©sent",objective:"DÃ©crire des habitudes et des actions simples.",rule:"Terminaisons: -e, -es, -e, -ons, -ez, -ent.",examples:[["Nous parlons franÃ§ais.","Hablamos francÃ©s."],["Ils regardent un film.","Miran una pelÃ­cula."]],keywords:["parler","habiter","travailler","prÃ©sent"]},
  {id:"a1-cuisine",level:"A1",group:"Actions quotidiennes",title:"La cuisine",objective:"Comprendre une recette et parler des aliments et des gestes culinaires.",rule:"Les recettes emploient frÃ©quemment lâ€™infinitif ou lâ€™impÃ©ratif: couper, ajouter, mÃ©langer, cuire.",examples:[["Coupez les lÃ©gumes.","Corte las verduras."],["Ajoutez un peu de sel.","Agregue un poco de sal."]],keywords:["aliments","couper","mÃ©langer","cuire"]},
  {id:"a2-pouvoir",level:"A2",group:"ModalitÃ©",title:"Pouvoir",objective:"Exprimer une capacitÃ©, une possibilitÃ© ou demander une permission.",rule:"Je peux, tu peux, il peut, nous pouvons, vous pouvez, ils peuvent.",examples:[["Pouvez-vous rÃ©pÃ©ter ?","Â¿Puede repetir?"],["Nous pouvons vous aider.","Podemos ayudarle."]],keywords:["pouvoir","capacitÃ©","permission","demande"]},
  {id:"a2-vouloir",level:"A2",group:"ModalitÃ©",title:"Vouloir",objective:"Exprimer un souhait, une intention ou une demande polie.",rule:"Je veuxâ€¦ est direct; Â« je voudraisâ€¦ Â» est plus poli dans un service.",examples:[["Je veux apprendre.","Quiero aprender."],["Je voudrais un cafÃ©.","Quisiera un cafÃ©."]],keywords:["vouloir","souhait","intention","politesse"]},
  {id:"a2-devoir",level:"A2",group:"ModalitÃ©",title:"Devoir",objective:"Exprimer une obligation, une nÃ©cessitÃ© ou un conseil fort.",rule:"Je dois, tu dois, il doit, nous devons, vous devez, ils doivent.",examples:[["Vous devez remplir ce formulaire.","Debe completar este formulario."],["Nous devons partir.","Debemos irnos."]],keywords:["devoir","obligation","nÃ©cessitÃ©","conseil"]},
  {id:"a2-information",level:"A2",group:"ModalitÃ©",title:"Obtenir des renseignements",objective:"Demander poliment une information dans un service public ou commercial.",rule:"Combinez une formule de politesse, une question prÃ©cise et une demande de confirmation.",examples:[["Pourriez-vous mâ€™indiquer le prix ?","Â¿PodrÃ­a indicarme el precio?"],["Jâ€™aimerais savoir siâ€¦","Me gustarÃ­a saber siâ€¦"]],keywords:["renseignements","service","prix","horaire"]},
  {id:"a2-ir",level:"A2",group:"Verbes au prÃ©sent",title:"Verbes en -IR",objective:"Conjuguer finir, choisir et rÃ©ussir au prÃ©sent.",rule:"Pour le modÃ¨le finir: -is, -is, -it, -issons, -issez, -issent.",examples:[["Nous choisissons le train.","Elegimos el tren."],["Elles finissent Ã  cinq heures.","Terminan a las cinco."]],keywords:["finir","choisir","rÃ©ussir","-issons"]},
  {id:"a2-oir",level:"A2",group:"Verbes au prÃ©sent",title:"Verbes en -OIR",objective:"Utiliser plusieurs verbes frÃ©quents aux formes irrÃ©guliÃ¨res.",rule:"Les verbes en -oir nâ€™ont pas un seul modÃ¨le: voir, recevoir et savoir doivent Ãªtre mÃ©morisÃ©s.",examples:[["Je vois la montagne.","Veo la montaÃ±a."],["Vous recevez un courriel.","Recibe un correo."]],keywords:["voir","savoir","recevoir","irrÃ©gulier"]},
  {id:"a2-dre",level:"A2",group:"Verbes au prÃ©sent",title:"Verbes en -RE et -DRE",objective:"Conjuguer prendre, comprendre, attendre et rÃ©pondre.",rule:"Les bases peuvent changer au pluriel: je prends, nous prenons; je comprends, nous comprenons.",examples:[["Je prends lâ€™autobus.","Tomo el autobÃºs."],["Vous comprenez la question.","Comprende la pregunta."]],keywords:["prendre","comprendre","attendre","rÃ©pondre"]},
  {id:"a2-aller",level:"A2",group:"Projets et pronoms",title:"Le verbe aller",objective:"Parler dâ€™un dÃ©placement et introduire un projet proche.",rule:"Je vais, tu vas, il va, nous allons, vous allez, ils vont.",examples:[["Nous allons au centre-ville.","Vamos al centro."],["OÃ¹ allez-vous ?","Â¿AdÃ³nde va?"]],keywords:["aller","destination","dÃ©placement","prÃ©sent"]},
  {id:"a2-futur",level:"A2",group:"Projets et pronoms",title:"Le futur proche",objective:"Exprimer une intention ou un Ã©vÃ©nement prochain.",rule:"Conjuguez aller au prÃ©sent, puis ajoutez lâ€™infinitif.",examples:[["Je vais appeler Marie.","Voy a llamar a Marie."],["Ils vont dÃ©mÃ©nager.","Van a mudarse."]],keywords:["aller + infinitif","projet","demain","bientÃ´t"]},
  {id:"a2-cod",level:"A2",group:"Projets et pronoms",title:"Pronoms directs",objective:"Remplacer une personne ou une chose directement liÃ©e au verbe.",rule:"Le, la, lâ€™ et les se placent avant le verbe conjuguÃ©.",examples:[["Je connais Paul. Je le connais.","Conozco a Paul. Lo conozco."],["Elle achÃ¨te les billets. Elle les achÃ¨te.","Compra los boletos. Los compra."]],keywords:["le","la","les","COD"]},
  {id:"a2-coi",level:"A2",group:"Projets et pronoms",title:"Pronoms indirects",objective:"Remplacer une personne introduite par Ã .",rule:"Lui remplace Ã  lui/Ã  elle; leur remplace Ã  eux/Ã  elles.",examples:[["Je parle Ã  Marie. Je lui parle.","Hablo con Marie. Le hablo."],["Nous Ã©crivons aux clients. Nous leur Ã©crivons.","Escribimos a los clientes. Les escribimos."]],keywords:["lui","leur","COI","Ã  quelquâ€™un"]},
  {id:"a2-temps",level:"A2",group:"Temps et comparaison",title:"PrÃ©positions de temps",objective:"Exprimer le dÃ©but, la durÃ©e prÃ©vue ou le temps nÃ©cessaire.",rule:"Depuis: action encore actuelle; pendant: durÃ©e achevÃ©e; pour: durÃ©e prÃ©vue; en: temps nÃ©cessaire.",examples:[["Jâ€™habite ici depuis deux ans.","Vivo aquÃ­ desde hace dos aÃ±os."],["Je pars pour trois semaines.","Me voy por tres semanas."]],keywords:["depuis","pendant","pour","en"]},
  {id:"a2-comparatif",level:"A2",group:"Temps et comparaison",title:"Le comparatif",objective:"Comparer des qualitÃ©s, des quantitÃ©s ou des actions.",rule:"Plusâ€¦ que, moinsâ€¦ que, aussiâ€¦ que; pour les noms: plus/moins/autant deâ€¦ que.",examples:[["Ce livre est plus intÃ©ressant que lâ€™autre.","Este libro es mÃ¡s interesante que el otro."],["Elle travaille autant que moi.","Trabaja tanto como yo."]],keywords:["plus","moins","aussi","que"]},
  {id:"a2-superlatif",level:"A2",group:"Temps et comparaison",title:"Le superlatif",objective:"Exprimer le degrÃ© maximal ou minimal dans un groupe.",rule:"Utilisez le/la/les plus ou le/la/les moins, en accordant lâ€™article.",examples:[["Câ€™est la plus grande ville.","Es la ciudad mÃ¡s grande."],["Voici le quartier le moins bruyant.","Este es el barrio menos ruidoso."]],keywords:["le plus","la plus","le moins","groupe"]},
  {id:"a2-reflexifs",level:"A2",group:"Temps et comparaison",title:"Verbes pronominaux",objective:"DÃ©crire la routine et les actions faites sur soi-mÃªme.",rule:"Me, te, se, nous, vous, se se placent avant le verbe.",examples:[["Je me lÃ¨ve Ã  sept heures.","Me levanto a las siete."],["Nous nous prÃ©parons.","Nos preparamos."]],keywords:["se lever","sâ€™habiller","se coucher","routine"]},
  {id:"a2-passe",level:"A2",group:"PassÃ© composÃ©",title:"PassÃ© composÃ© avec avoir",objective:"Raconter une action terminÃ©e dans le passÃ©.",rule:"Sujet + avoir au prÃ©sent + participe passÃ©; -er devient -Ã©, -ir devient souvent -i.",examples:[["Jâ€™ai terminÃ© mon travail.","TerminÃ© mi trabajo."],["Nous avons choisi un restaurant.","Elegimos un restaurante."]],keywords:["avoir","participe passÃ©","hier","action terminÃ©e"]},
  {id:"a2-participes",level:"A2",group:"PassÃ© composÃ©",title:"Participes passÃ©s frÃ©quents",objective:"MÃ©moriser les formes irrÃ©guliÃ¨res nÃ©cessaires pour raconter.",rule:"Faire-fait, prendre-pris, voir-vu, avoir-eu, lire-lu, boire-bu.",examples:[["Elle a fait un gÃ¢teau.","Hizo un pastel."],["Ils ont pris le mÃ©tro.","Tomaron el metro."]],keywords:["fait","pris","vu","eu","lu"]},
  {id:"a1-svo",level:"A1",group:"Fondations grammaticales",title:"Pronoms sujets et ordre SVO",objective:"Construire une phrase simple dans lâ€™ordre naturel du franÃ§ais.",rule:"La structure de base est sujet + verbe + complÃ©ment; le sujet est presque toujours exprimÃ©.",examples:[["Marie prÃ©pare le repas.","Marie prepara la comida."],["Elle prÃ©pare le repas.","Ella prepara la comida."]],keywords:["je","tu","il","elle","SVO"]},
  {id:"a1-cest",level:"A1",group:"Fondations grammaticales",title:"Câ€™est et quâ€™est-ce que câ€™est",objective:"Identifier et prÃ©senter une personne ou une chose.",rule:"Â« Câ€™est Â» identifie au singulier; Â« ce sont Â» identifie au pluriel.",examples:[["Quâ€™est-ce que câ€™est ? Câ€™est un livre.","Â¿QuÃ© es? Es un libro."],["Ce sont mes amis.","Son mis amigos."]],keywords:["câ€™est","ce sont","identifier","prÃ©senter"]},
  {id:"a1-voyelles",level:"A1",group:"Prononciation",title:"Voyelles orales",objective:"Distinguer des voyelles proches dans des mots frÃ©quents.",rule:"Ã‰coutez la position des lÃ¨vres et la durÃ©e; rÃ©pÃ©tez dâ€™abord lentement, puis dans une phrase.",examples:[["tu / tout","u francesa / u"],["mot / mode","palabra / moda"]],keywords:["u/ou","Ã©/Ã¨","o/É”","paires minimales"]},
  {id:"a1-nasales",level:"A1",group:"Prononciation",title:"Voyelles nasales",objective:"ReconnaÃ®tre et produire les sons Ã©crits an/en, on et in/ain.",rule:"Lâ€™air passe aussi par le nez et le n final nâ€™est gÃ©nÃ©ralement pas prononcÃ© sÃ©parÃ©ment.",examples:[["vent / vin","viento / vino"],["bon pain","buen pan"]],keywords:["an","on","in","nasal"]},
  {id:"a1-liaison",level:"A1",group:"Prononciation",title:"Liaison et Ã©lision",objective:"EnchaÃ®ner naturellement les mots frÃ©quents.",rule:"Devant une voyelle, certaines consonnes finales se lient; je devient jâ€™, ne devient nâ€™.",examples:[["Nous avons","nous-z-avons"],["Jâ€™ai un ami.","Tengo un amigo."]],keywords:["liaison","Ã©lision","enchaÃ®nement","voyelle"]},
  {id:"a1-famille",level:"A1",group:"Se prÃ©senter",title:"La famille",objective:"PrÃ©senter les membres dâ€™une famille et leurs relations.",rule:"Combinez les noms de famille, les possessifs et Ãªtre/avoir pour dÃ©crire.",examples:[["Ma sÅ“ur a deux enfants.","Mi hermana tiene dos hijos."],["Voici mes grands-parents.","Estos son mis abuelos."]],keywords:["parents","frÃ¨re","sÅ“ur","grands-parents"]},
  {id:"a1-etre-questions",level:"A1",group:"Questions",title:"ÃŠtre : nÃ©gation et questions",objective:"Nier et interroger une identitÃ© ou un Ã©tat.",rule:"Neâ€¦pas encadre Ãªtre; lâ€™inversion donne Â« Es-tuâ€¦ ? Â», Â« ÃŠtes-vousâ€¦ ? Â».",examples:[["Je ne suis pas disponible.","No estoy disponible."],["ÃŠtes-vous prÃªt ?","Â¿EstÃ¡ listo?"]],keywords:["ne suis pas","es-tu","est-il","Ãªtes-vous"]},
  {id:"a1-avoir-expressions",level:"A1",group:"Avoir et demander",title:"Expressions avec avoir",objective:"Exprimer sensations, besoins et Ã©motions avec avoir.",rule:"Le franÃ§ais utilise avoir lÃ  oÃ¹ lâ€™espagnol peut utiliser tener ou estar.",examples:[["Jâ€™ai faim et jâ€™ai soif.","Tengo hambre y sed."],["Elle a besoin dâ€™aide.","Necesita ayuda."]],keywords:["faim","soif","besoin","envie","peur"]},
  {id:"a1-corps",level:"A1",group:"Avoir et demander",title:"Le corps et avoir mal",objective:"Nommer les parties du corps et expliquer une douleur.",rule:"Avoir mal Ã  + article contractÃ©: au dos, Ã  la tÃªte, aux pieds.",examples:[["Jâ€™ai mal au dos.","Me duele la espalda."],["Il a mal aux yeux.","Le duelen los ojos."]],keywords:["tÃªte","dos","bras","jambes","avoir mal"]},
  {id:"a1-genre-noms",level:"A1",group:"Objets et maison",title:"Genre des noms",objective:"MÃ©moriser un nom avec son article et reconnaÃ®tre quelques terminaisons utiles.",rule:"Apprenez toujours le nom avec le/la; -tion est souvent fÃ©minin et -ment souvent masculin.",examples:[["la nation","la naciÃ³n"],["le bÃ¢timent","el edificio"]],keywords:["le","la","terminaisons","nom"]},
  {id:"a1-quantites",level:"A1",group:"Objets et maison",title:"QuantitÃ©s + de",objective:"Exprimer une mesure ou une quantitÃ© prÃ©cise.",rule:"AprÃ¨s beaucoup, un peu, un kilo, une tasse ou une bouteille, utilisez de/dâ€™.",examples:[["une bouteille dâ€™eau","una botella de agua"],["beaucoup de lÃ©gumes","muchas verduras"]],keywords:["kilo","bouteille","tasse","beaucoup de"]},
  {id:"a1-il-y-a",level:"A1",group:"Objets et maison",title:"Il y a",objective:"DÃ©crire ce qui existe ou manque dans un lieu.",rule:"Il y a; il nâ€™y a pas de; est-ce quâ€™il y aâ€¦ ? ou y a-t-ilâ€¦ ?",examples:[["Il y a une cuisine.","Hay una cocina."],["Il nâ€™y a pas de balcon.","No hay balcÃ³n."]],keywords:["il y a","pas de","maison","existence"]},
  {id:"a1-er-changements",level:"A1",group:"Actions quotidiennes",title:"Verbes -ER avec changement",objective:"Conjuguer manger, commencer, acheter et prÃ©fÃ©rer sans appliquer aveuglÃ©ment un seul modÃ¨le.",rule:"Certains verbes adaptent lâ€™orthographe pour conserver le son ou changent de voyelle.",examples:[["Nous mangeons ensemble.","Comemos juntos."],["Je prÃ©fÃ¨re le thÃ©.","Prefiero el tÃ©."]],keywords:["mangeons","commenÃ§ons","achÃ¨te","prÃ©fÃ¨re"]},
  {id:"a1-imperatif",level:"A1",group:"Actions quotidiennes",title:"Lâ€™impÃ©ratif",objective:"Donner une instruction ou un conseil avec tu, nous ou vous.",rule:"Supprimez le sujet; Ã  la forme nÃ©gative, neâ€¦pas entoure le verbe.",examples:[["MÃ©langez les ingrÃ©dients.","Mezcle los ingredientes."],["Ne mange pas trop vite !","Â¡No comas tan rÃ¡pido!"]],keywords:["ordre","conseil","tu","nous","vous"]},
  {id:"a2-modal-formes",level:"A2",group:"ModalitÃ©",title:"Modaux : nÃ©gation et interrogation",objective:"Transformer pouvoir, vouloir et devoir dans les trois formes.",rule:"Neâ€¦pas entoure le modal; lâ€™inversion place le pronom aprÃ¨s le verbe.",examples:[["Je ne peux pas venir.","No puedo venir."],["Doit-on rÃ©server ?","Â¿Hay que reservar?"]],keywords:["peut-on","voulez-vous","doit-on","neâ€¦pas"]},
  {id:"a2-invitations",level:"A2",group:"Communication",title:"Inviter, accepter et refuser",objective:"GÃ©rer une invitation avec le registre adaptÃ© et proposer une solution.",rule:"Acceptez clairement ou refusez avec excuse et contre-proposition.",examples:[["Avec plaisir !","Â¡Con gusto!"],["Je suis dÃ©solÃ©, mais je suis occupÃ©. Une autre fois ?","Lo siento, estoy ocupado. Â¿Otro dÃ­a?"]],keywords:["inviter","accepter","refuser","contre-proposition"]},
  {id:"a2-faire-dire",level:"A2",group:"Verbes au prÃ©sent",title:"Faire et dire",objective:"Parler dâ€™activitÃ©s, de mÃ©tÃ©o et rapporter une parole.",rule:"Je fais/nous faisons/ils font; je dis/nous disons/vous dites.",examples:[["Il fait froid.","Hace frÃ­o."],["Vous dites la vÃ©ritÃ©.","Dice la verdad."]],keywords:["faire","dire","mÃ©tÃ©o","activitÃ©"]},
  {id:"a2-venir-tenir",level:"A2",group:"Verbes au prÃ©sent",title:"Venir et tenir",objective:"Utiliser deux familles irrÃ©guliÃ¨res frÃ©quentes.",rule:"Je viens/nous venons/ils viennent; je tiens/nous tenons/ils tiennent.",examples:[["Elle vient demain.","Viene maÃ±ana."],["Nous tenons notre promesse.","Cumplimos nuestra promesa."]],keywords:["venir","tenir","viennent","tiennent"]},
  {id:"a2-temps-etendu",level:"A2",group:"Temps et comparaison",title:"Dans, il y a, dÃ¨s et jusquâ€™Ã ",objective:"Situer prÃ©cisÃ©ment une action dans le passÃ© ou le futur.",rule:"Dans = futur; il y a = passÃ©; dÃ¨s = point de dÃ©part; jusquâ€™Ã  = limite.",examples:[["Je pars dans deux jours.","Me voy dentro de dos dÃ­as."],["Il est arrivÃ© il y a une heure.","LlegÃ³ hace una hora."]],keywords:["dans","il y a","dÃ¨s","jusquâ€™Ã "]},
  {id:"a2-pronom-y",level:"A2",group:"Projets et pronoms",title:"Le pronom y",objective:"Remplacer un lieu ou Ã  + chose.",rule:"Y ne remplace gÃ©nÃ©ralement pas une personne et se place avant le verbe.",examples:[["Je vais au marchÃ©. Jâ€™y vais.","Voy al mercado. Voy allÃ­."],["Je pense Ã  mon projet. Jâ€™y pense.","Pienso en mi proyecto."]],keywords:["y","lieu","Ã  + chose","pronom"]},
  {id:"a2-pronom-en",level:"A2",group:"Projets et pronoms",title:"Le pronom en",objective:"Remplacer de + chose ou une quantitÃ©.",rule:"Conservez la quantitÃ© aprÃ¨s le verbe: jâ€™en achÃ¨te trois.",examples:[["Je parle de ce livre. Jâ€™en parle.","Hablo de este libro. Hablo de Ã©l."],["Jâ€™achÃ¨te trois pommes. Jâ€™en achÃ¨te trois.","Compro tres manzanas. Compro tres."]],keywords:["en","de + chose","quantitÃ©","pronom"]},
  {id:"a2-pronoms-ordre",level:"A2",group:"Projets et pronoms",title:"Ordre des pronoms",objective:"Combiner plusieurs pronoms sans hÃ©siter.",rule:"Ordre utile: me/te/nous/vous, le/la/les, lui/leur, y, en.",examples:[["Je le lui donne.","Se lo doy."],["Nous y en achetons.","Compramos allÃ­ algunos."]],keywords:["ordre","le lui","y en","double pronom"]},
  {id:"a2-regime",level:"A2",group:"Projets et pronoms",title:"Verbes avec Ã , de ou sans prÃ©position",objective:"Choisir la construction qui suit un verbe.",rule:"Commencer Ã , avoir besoin de, aimer + infinitif: apprenez la construction avec le verbe.",examples:[["Elle commence Ã  travailler.","Empieza a trabajar."],["Nous avons besoin de partir.","Necesitamos irnos."]],keywords:["Ã ","de","infinitif","construction"]},
  {id:"a2-reflexifs-formes",level:"A2",group:"Temps et comparaison",title:"Pronominaux : nÃ©gation et questions",objective:"Nier et interroger une action pronominale.",rule:"Le pronom reste devant le verbe: je ne me lÃ¨ve pas; vous levez-vous ?",examples:[["Elle ne se couche pas tard.","No se acuesta tarde."],["Vous prÃ©parez-vous ?","Â¿Se prepara?"]],keywords:["ne seâ€¦pas","vousâ€¦-vous","routine","question"]},
  {id:"a2-passe-formes",level:"A2",group:"PassÃ© composÃ©",title:"PassÃ© : nÃ©gation et questions",objective:"Nier et interroger une action passÃ©e.",rule:"Neâ€¦pas entoure lâ€™auxiliaire; lâ€™inversion concerne lâ€™auxiliaire.",examples:[["Je nâ€™ai pas travaillÃ©.","No trabajÃ©."],["Avez-vous compris ?","Â¿ComprendiÃ³?"]],keywords:["nâ€™ai pas","avez-vous","auxiliaire","passÃ©"]},
  {id:"a2-passe-etre",level:"A2",group:"PassÃ© composÃ©",title:"PassÃ© composÃ© avec Ãªtre",objective:"Raconter les dÃ©placements et accorder le participe avec le sujet.",rule:"Certains verbes de mouvement utilisent Ãªtre; le participe sâ€™accorde en genre et en nombre.",examples:[["Elle est arrivÃ©e hier.","LlegÃ³ ayer."],["Ils sont partis tÃ´t.","Se fueron temprano."]],keywords:["Ãªtre","arrivÃ©e","partis","accord"]},
  {id:"a2-vandertramp",level:"A2",group:"PassÃ© composÃ©",title:"Vandertramp : les verbes avec Ãªtre",objective:"MÃ©moriser les verbes usuels de dÃ©placement ou de changement dâ€™Ã©tat qui utilisent Ãªtre au passÃ© composÃ©.",rule:"La mnemotecnia Vandertramp ayuda, pero no es una regla absoluta: aller, venir, arriver, partir, entrer, sortir, monter, descendre, naÃ®tre, mourir, tomber, rester, retourner, passer y rentrer suelen usar Ãªtre cuando describen movimiento o cambio. Los verbos pronominales tambiÃ©n usan Ãªtre. El participio concuerda: elle est arrivÃ©e, ils sont partis.",examples:[["Nous sommes arrivÃ©s Ã  MontrÃ©al.","Llegamos a Montreal."],["Elle est sortie; elles se sont levÃ©es tÃ´t.","Ella saliÃ³; ellas se levantaron temprano."]],keywords:["Vandertramp","Ãªtre","accord","arrivÃ©(e)(s)","verbes pronominaux"]},
  {id:"a2-passe-pronominal",level:"A2",group:"PassÃ© composÃ©",title:"Pronominaux au passÃ©",objective:"Raconter une routine ou une action pronominale terminÃ©e.",rule:"Les verbes pronominaux utilisent Ãªtre: je me suis levÃ©(e).",examples:[["Elle sâ€™est prÃ©parÃ©e.","Se preparÃ³."],["Nous nous sommes couchÃ©s tard.","Nos acostamos tarde."]],keywords:["me suis","sâ€™est","nous sommes","accord"]},
  {id:"a2-auxiliaire",level:"A2",group:"PassÃ© composÃ©",title:"Choisir avoir ou Ãªtre",objective:"SÃ©lectionner lâ€™auxiliaire et corriger les erreurs frÃ©quentes.",rule:"La plupart des verbes utilisent avoir; les pronominaux et certains dÃ©placements utilisent Ãªtre.",examples:[["Jâ€™ai pris le mÃ©tro.","TomÃ© el metro."],["Je suis allÃ© au bureau.","Fui a la oficina."]],keywords:["avoir","Ãªtre","choix","transitif"]},
  {id:"a2-hier-demain",level:"A2",group:"IntÃ©gration",title:"Hier, aujourdâ€™hui, demain",objective:"Relier passÃ© composÃ©, prÃ©sent et futur proche dans un rÃ©cit.",rule:"Choisissez le temps selon le repÃ¨re temporel et maintenez une chronologie claire.",examples:[["Hier, jâ€™ai travaillÃ©; aujourdâ€™hui, je me repose.","Ayer trabajÃ©; hoy descanso."],["Demain, je vais sortir.","MaÃ±ana voy a salir."]],keywords:["hier","aujourdâ€™hui","demain","chronologie"]},
  {id:"a2-prononciation",level:"A2",group:"Prononciation",title:"Formes qui se prononcent pareil",objective:"Distinguer par le contexte des formes verbales homophones.",rule:"Parle, parles et parlent se prononcent souvent pareil; lâ€™Ã©crit dÃ©pend du sujet.",examples:[["je peux / il peut","puedo / puede"],["aller / allÃ©","ir / ido"]],keywords:["homophones","-ent muet","-Ã©/-er","contexte"]},
  {id:"b1-imparfait",level:"B1",group:"Raconter au passÃ©",title:"Lâ€™imparfait",objective:"DÃ©crire une habitude, un dÃ©cor, une Ã©motion ou une action en cours dans le passÃ©.",rule:"Prenez la forme nous au prÃ©sent, retirez -ons et ajoutez -ais, -ais, -ait, -ions, -iez, -aient. ÃŠtre est irrÃ©gulier : jâ€™Ã©tais.",examples:[["Quand jâ€™Ã©tais enfant, je jouais dehors.","Cuando era niÃ±o, jugaba afuera."],["Il pleuvait et la rue Ã©tait vide.","LlovÃ­a y la calle estaba vacÃ­a."]],keywords:["habitude","description","contexte","Ã©tait"]},
  {id:"b1-passe-imparfait",level:"B1",group:"Raconter au passÃ©",title:"PassÃ© composÃ© ou imparfait",objective:"Distinguer le cadre ou lâ€™action en cours del hecho puntual que avanza el relato.",rule:"Lâ€™imparfait crÃ©e le dÃ©cor ou une action en cours; le passÃ© composÃ© marque un fait terminÃ©, bref ou soudain.",examples:[["Je lisais quand le tÃ©lÃ©phone a sonnÃ©.","LeÃ­a cuando sonÃ³ el telÃ©fono."],["Tous les Ã©tÃ©s, nous allions Ã  la mer.","Todos los veranos Ã­bamos al mar."]],keywords:["pendant que","soudain","cadre","Ã©vÃ©nement"]},
  {id:"b1-pqp",level:"B1",group:"Raconter au passÃ©",title:"Le plus-que-parfait",objective:"Exprimer une action terminÃ©e avant une autre action passÃ©e.",rule:"Imparfait de avoir ou Ãªtre + participe passÃ© : jâ€™avais fini, elle Ã©tait partie.",examples:[["Le film avait dÃ©jÃ  commencÃ© quand nous sommes arrivÃ©s.","La pelÃ­cula ya habÃ­a comenzado cuando llegamos."],["Elle Ã©tait partie avant mon appel.","Ella se habÃ­a ido antes de mi llamada."]],keywords:["avant","dÃ©jÃ ","avait","Ã©tait"]},
  {id:"b1-conditionnel",level:"B1",group:"HypothÃ¨ses et conseils",title:"Le conditionnel prÃ©sent et passÃ©",objective:"Formuler un souhait, un conseil, una hipÃ³tesis o un arrepentimiento.",rule:"Futur radical + terminaisons de lâ€™imparfait : je pourrais. Avec si : si + imparfait, conditionnel; si + plus-que-parfait, conditionnel passÃ©.",examples:[["Si jâ€™avais plus de temps, je voyagerais.","Si tuviera mÃ¡s tiempo, viajarÃ­a."],["Si tu mâ€™avais prÃ©venu, je serais venu.","Si me hubieras avisado, habrÃ­a venido."]],keywords:["si","pourrais","devrais","jâ€™aurais"]},
  {id:"b1-subjonctif",level:"B1",group:"Opinion et nÃ©cessitÃ©",title:"Le subjonctif",objective:"Exprimer la nÃ©cessitÃ©, le doute, lâ€™Ã©motion, el deseo o una finalidad.",rule:"AprÃ¨s il faut que, je veux que, bien que, pour queâ€¦ : que je fasse, que nous finissions. MÃ©morisez Ãªtre, avoir, aller, faire, pouvoir, vouloir et venir.",examples:[["Il faut que nous partions Ã  lâ€™heure.","Es necesario que salgamos a tiempo."],["Je doute quâ€™elle soit disponible.","Dudo que ella estÃ© disponible."]],keywords:["il faut que","bien que","pour que","soit"]},
  {id:"b1-argumentation",level:"B1",group:"TEF / TCF",title:"Convaincre et rÃ©diger une opinion",objective:"Organiser una opiniÃ³n clara con argumentos, contraste y conclusiÃ³n.",rule:"Annoncez le sujet, dÃ©veloppez une thÃ¨se et une antithÃ¨se, donnez votre position puis concluez. Utilisez dâ€™abord, de plus, cependant, en revanche et en conclusion.",examples:[["Ã€ mon avis, le tÃ©lÃ©travail offre plus de flexibilitÃ©.","En mi opiniÃ³n, el teletrabajo ofrece mÃ¡s flexibilidad."],["Cependant, il peut isoler certains employÃ©s.","Sin embargo, puede aislar a algunos empleados."]],keywords:["Ã  mon avis","cependant","en revanche","conclusion"]},
];

export const courseExercises: CourseExercise[] = [
  {id:"e01",level:"A1",skill:"Vocabulaire",mode:"choice",prompt:"Quel mot correspond Ã  Â« jueves Â» ?",answer:"jeudi",options:["mardi","jeudi","samedi"],hint:"Les jours de la semaine."},
  {id:"e02",level:"A1",skill:"Vocabulaire",mode:"fill",prompt:"Le mois aprÃ¨s avril est ___.",answer:"mai",hint:"Les mois de lâ€™annÃ©e."},
  {id:"e03",level:"A1",skill:"Temps",mode:"choice",prompt:"80 sâ€™Ã©critâ€¦",answer:"quatre-vingts",options:["soixante-dix","quatre-vingts","quatre-vingt-dix"],hint:"Quatre fois vingt; le s disparaÃ®t si un autre nombre suit."},
  {id:"e04",level:"A1",skill:"Communication",mode:"reorder",prompt:"Remettez la prÃ©sentation en ordre.",answer:"Je mâ€™appelle Sofia",tokens:["Sofia","mâ€™appelle","Je"],hint:"Sujet + pronom + verbe + prÃ©nom."},
  {id:"e05",level:"A1",skill:"Verbes",mode:"fill",prompt:"Nous ___ Ã©tudiants. (Ãªtre)",answer:"sommes",hint:"ÃŠtre avec nous."},
  {id:"e06",level:"A1",skill:"Grammaire",mode:"transform",prompt:"Mettez au fÃ©minin : Il est sportif.",answer:"Elle est sportive",hint:"Sportif devient sportive."},
  {id:"e07",level:"A1",skill:"Communication",mode:"choice",prompt:"Quelle phrase est correcte pour une profession ?",answer:"Elle est mÃ©decin.",options:["Elle est une mÃ©decin.","Elle est mÃ©decin.","Elle a mÃ©decin."],hint:"AprÃ¨s Ãªtre, la profession est gÃ©nÃ©ralement sans article."},
  {id:"e08",level:"A1",skill:"Grammaire",mode:"fill",prompt:"Je vais ___ Paul ce soir.",answer:"chez",hint:"Lieu associÃ© Ã  une personne."},
  {id:"e09",level:"A1",skill:"Temps",mode:"choice",prompt:"8 h 30 se ditâ€¦",answer:"huit heures et demie",options:["huit heures et quart","huit heures et demie","neuf heures moins le quart"],hint:"Trente minutes = et demie."},
  {id:"e10",level:"A1",skill:"Grammaire",mode:"fill",prompt:"Câ€™est ___ sÅ“ur. (je)",answer:"ma",hint:"SÅ“ur est fÃ©minin singulier."},
  {id:"e11",level:"A1",skill:"Verbes",mode:"fill",prompt:"Vous ___ une rÃ©servation. (avoir)",answer:"avez",hint:"Avoir avec vous."},
  {id:"e12",level:"A1",skill:"Grammaire",mode:"choice",prompt:"Je vois pour la premiÃ¨re foisâ€¦",answer:"un chien",options:["le chien","un chien","du chien"],hint:"On prÃ©sente un Ã©lÃ©ment comptable non identifiÃ©."},
  {id:"e13",level:"A1",skill:"Grammaire",mode:"fill",prompt:"Nous allons ___ marchÃ©.",answer:"au",hint:"Ã€ + le = au."},
  {id:"e14",level:"A1",skill:"Grammaire",mode:"fill",prompt:"Je bois ___ eau.",answer:"de lâ€™",hint:"Partitif devant une voyelle."},
  {id:"e15",level:"A1",skill:"Grammaire",mode:"transform",prompt:"Mettez Ã  la nÃ©gation : Jâ€™ai une voiture.",answer:"Je nâ€™ai pas de voiture",hint:"AprÃ¨s pas, lâ€™article indÃ©fini devient de."},
  {id:"e16",level:"A1",skill:"Communication",mode:"reorder",prompt:"Construisez une question sur le lieu.",answer:"OÃ¹ est-ce que tu habites",tokens:["tu","habites","OÃ¹","est-ce","que"],hint:"Mot interrogatif + est-ce que + sujet + verbe."},
  {id:"e17",level:"A1",skill:"Verbes",mode:"fill",prompt:"Ils ___ franÃ§ais chaque jour. (parler)",answer:"parlent",hint:"La terminaison -ent ne se prononce pas."},
  {id:"e18",level:"A1",skill:"Verbes",mode:"transform",prompt:"Conjuguez avec nous : Je regarde la tÃ©lÃ©vision.",answer:"Nous regardons la tÃ©lÃ©vision",hint:"Nous + verbe en -ons."},
  {id:"e19",level:"A1",skill:"Vocabulaire",mode:"choice",prompt:"Quel verbe signifie Â« cortar Â» ?",answer:"couper",options:["cuire","couper","mÃ©langer"],hint:"Un geste de cuisine."},
  {id:"e20",level:"A1",skill:"Communication",mode:"reorder",prompt:"Donnez une instruction de cuisine.",answer:"Ajoutez un peu de sel",tokens:["de","sel","Ajoutez","un","peu"],hint:"ImpÃ©ratif + complÃ©ment."},
  {id:"e21",level:"A1",skill:"Vocabulaire",mode:"fill",prompt:"La saison aprÃ¨s lâ€™hiver est ___.",answer:"le printemps",hint:"Mars, avril et mai."},
  {id:"e22",level:"A1",skill:"Communication",mode:"choice",prompt:"Formule formelle pour prendre congÃ© :",answer:"Au revoir, bonne journÃ©e.",options:["Salut !","Au revoir, bonne journÃ©e.","Coucou !"],hint:"Choisissez une formule adaptÃ©e Ã  vous."},
  {id:"e23",level:"A1",skill:"Grammaire",mode:"transform",prompt:"Mettez au pluriel : Câ€™est son livre.",answer:"Ce sont ses livres",hint:"Son devient ses; câ€™est devient ce sont."},
  {id:"e24",level:"A1",skill:"Temps",mode:"fill",prompt:"La rÃ©union commence ___ neuf heures.",answer:"Ã ",hint:"Ã€ + heure prÃ©cise."},
  {id:"e25",level:"A2",skill:"Verbes",mode:"fill",prompt:"Nous ___ vous aider. (pouvoir)",answer:"pouvons",hint:"Pouvoir avec nous."},
  {id:"e26",level:"A2",skill:"Communication",mode:"choice",prompt:"Demande la plus polie au cafÃ© :",answer:"Je voudrais un cafÃ©, sâ€™il vous plaÃ®t.",options:["Je veux un cafÃ©.","Je voudrais un cafÃ©, sâ€™il vous plaÃ®t.","Donnez-moi cafÃ©."],hint:"Le conditionnel de politesse adoucit la demande."},
  {id:"e27",level:"A2",skill:"Verbes",mode:"fill",prompt:"Vous ___ prÃ©senter une piÃ¨ce dâ€™identitÃ©. (devoir)",answer:"devez",hint:"Devoir avec vous."},
  {id:"e28",level:"A2",skill:"Communication",mode:"reorder",prompt:"Demandez un renseignement poliment.",answer:"Pourriez-vous mâ€™indiquer le prix",tokens:["le","mâ€™indiquer","Pourriez-vous","prix"],hint:"Conditionnel + pronom + infinitif."},
  {id:"e29",level:"A2",skill:"Verbes",mode:"fill",prompt:"Elles ___ leur travail. (finir)",answer:"finissent",hint:"Finir avec elles: -issent."},
  {id:"e30",level:"A2",skill:"Verbes",mode:"fill",prompt:"Nous ___ le train. (choisir)",answer:"choisissons",hint:"Choisir avec nous: -issons."},
  {id:"e31",level:"A2",skill:"Verbes",mode:"fill",prompt:"Je ___ la montagne. (voir)",answer:"vois",hint:"Voir: je vois."},
  {id:"e32",level:"A2",skill:"Verbes",mode:"fill",prompt:"Vous ___ la rÃ©ponse. (savoir)",answer:"savez",hint:"Savoir avec vous."},
  {id:"e33",level:"A2",skill:"Verbes",mode:"fill",prompt:"Ils ___ lâ€™autobus. (prendre)",answer:"prennent",hint:"Deux n au pluriel ils/elles."},
  {id:"e34",level:"A2",skill:"Grammaire",mode:"transform",prompt:"Mettez Ã  la nÃ©gation : Elle comprend la question.",answer:"Elle ne comprend pas la question",hint:"Neâ€¦ pas encadre le verbe."},
  {id:"e35",level:"A2",skill:"Verbes",mode:"fill",prompt:"Nous ___ au musÃ©e. (aller)",answer:"allons",hint:"Aller avec nous."},
  {id:"e36",level:"A2",skill:"Temps",mode:"reorder",prompt:"Exprimez un projet proche.",answer:"Je vais chercher un appartement",tokens:["un","vais","Je","appartement","chercher"],hint:"Aller au prÃ©sent + infinitif."},
  {id:"e37",level:"A2",skill:"Grammaire",mode:"transform",prompt:"Remplacez Â« le film Â» : Je regarde le film.",answer:"Je le regarde",hint:"Le pronom direct se place avant le verbe."},
  {id:"e38",level:"A2",skill:"Grammaire",mode:"transform",prompt:"Remplacez Â« Ã  Marie Â» : Je tÃ©lÃ©phone Ã  Marie.",answer:"Je lui tÃ©lÃ©phone",hint:"Ã€ une personne = lui."},
  {id:"e39",level:"A2",skill:"Temps",mode:"fill",prompt:"Jâ€™habite au Canada ___ 2023.",answer:"depuis",hint:"Lâ€™action continue aujourdâ€™hui."},
  {id:"e40",level:"A2",skill:"Temps",mode:"choice",prompt:"Je suis parti ___ deux semaines, puis je suis revenu.",answer:"pendant",options:["depuis","pendant","en"],hint:"DurÃ©e achevÃ©e."},
  {id:"e41",level:"A2",skill:"Grammaire",mode:"fill",prompt:"Ce trajet est ___ rapide que lâ€™autre.",answer:"plus",hint:"Comparatif de supÃ©rioritÃ©."},
  {id:"e42",level:"A2",skill:"Grammaire",mode:"transform",prompt:"Exprimez le maximum : Cette ville est grande dans la rÃ©gion.",answer:"Câ€™est la plus grande ville de la rÃ©gion",hint:"La + plus + adjectif fÃ©minin."},
  {id:"e43",level:"A2",skill:"Verbes",mode:"fill",prompt:"Je me ___ Ã  sept heures. (lever)",answer:"lÃ¨ve",hint:"Le e devient Ã¨ devant une syllabe muette."},
  {id:"e44",level:"A2",skill:"Verbes",mode:"transform",prompt:"Mettez au passÃ© composÃ© : Nous terminons le projet.",answer:"Nous avons terminÃ© le projet",hint:"Avoir au prÃ©sent + terminÃ©."},
  {id:"e45",level:"A2",skill:"Verbes",mode:"fill",prompt:"Elle a ___ un gÃ¢teau. (faire)",answer:"fait",hint:"Participe passÃ© irrÃ©gulier."},
  {id:"e46",level:"A2",skill:"Verbes",mode:"fill",prompt:"Ils ont ___ le mÃ©tro. (prendre)",answer:"pris",hint:"Participe passÃ© de prendre."},
  {id:"e47",level:"A2",skill:"Communication",mode:"choice",prompt:"Pour demander une confirmation :",answer:"Est-ce que le prix comprend les taxes ?",options:["Le prix taxes.","Est-ce que le prix comprend les taxes ?","Pourquoi prix ?"],hint:"Question complÃ¨te et prÃ©cise."},
  {id:"e48",level:"A2",skill:"Grammaire",mode:"transform",prompt:"Remplacez Â« les clients Â» : Nous Ã©crivons aux clients.",answer:"Nous leur Ã©crivons",hint:"Ã€ plusieurs personnes = leur."},
  {id:"e49",level:"A2",skill:"Temps",mode:"fill",prompt:"Je vais au QuÃ©bec ___ trois mois. (durÃ©e prÃ©vue)",answer:"pour",hint:"Pour + durÃ©e prÃ©vue."},
  {id:"e50",level:"A2",skill:"Grammaire",mode:"choice",prompt:"Comparaison dâ€™Ã©galitÃ© correcte :",answer:"Elle est aussi patiente que lui.",options:["Elle est autant patiente que lui.","Elle est aussi patiente que lui.","Elle est si patiente de lui."],hint:"Aussi + adjectif + que."},
  {id:"e51",level:"A2",skill:"Verbes",mode:"fill",prompt:"Marie ___ Ã  la gare Ã  huit heures. (arriver)",answer:"est arrivÃ©e",hint:"Arriver se construit avec Ãªtre; ajoute -e pour elle."},
  {id:"e52",level:"A2",skill:"Verbes",mode:"fill",prompt:"Nous ___ tÃ´t ce matin. (partir)",answer:"sommes partis",hint:"Partir utilise Ãªtre; -s marque nous au masculin o grupo mixto."},
  {id:"e53",level:"A2",skill:"Grammaire",mode:"choice",prompt:"Choisissez la phrase correcte :",answer:"Elles sont descendues du bus.",options:["Elles ont descendues du bus.","Elles sont descendues du bus.","Elles sont descendu du bus."],hint:"Descendre de un lugar usa Ãªtre; elles exige -es."},
  {id:"e54",level:"A2",skill:"Verbes",mode:"transform",prompt:"Mettez au passÃ© composÃ© : Elle entre dans la maison.",answer:"Elle est entrÃ©e dans la maison",hint:"Entrer describe movimiento hacia un lugar: Ãªtre + participio concordado."},
  {id:"e55",level:"A2",skill:"Verbes",mode:"fill",prompt:"Ils se ___ Ã  six heures. (lever)",answer:"sont levÃ©s",hint:"Todo verbo pronominal usa Ãªtre en passÃ© composÃ©."},
  {id:"e56",level:"A2",skill:"Grammaire",mode:"choice",prompt:"Quelle phrase est correcte pour une action transitiva ?",answer:"Jâ€™ai sorti les livres du sac.",options:["Je suis sorti les livres du sac.","Jâ€™ai sorti les livres du sac.","Je suis sortie les livres du sac."],hint:"Sortir + objeto directo usa avoir; sin objeto, Je suis sorti(e)."},
  {id:"b1-01",level:"B1",skill:"Verbes",mode:"fill",prompt:"Quand jâ€™Ã©tais enfant, je ___ dehors. (jouer)",answer:"jouais",hint:"Habitude au passÃ© : imparfait avec je."},
  {id:"b1-02",level:"B1",skill:"Temps",mode:"choice",prompt:"Choisissez le bon temps : Pendant que nous ___, la lumiÃ¨re sâ€™est Ã©teinte.",answer:"dÃ®nions",options:["avons dÃ®nÃ©","dÃ®nions","avions dÃ®nÃ©"],hint:"Action en cours = imparfait."},
  {id:"b1-03",level:"B1",skill:"Temps",mode:"fill",prompt:"Il ___ froid et soudain la neige ___. (faire / commencer)",answer:"faisait / a commencÃ©",hint:"DÃ©cor : imparfait; Ã©vÃ©nement soudain : passÃ© composÃ©."},
  {id:"b1-04",level:"B1",skill:"Grammaire",mode:"transform",prompt:"RÃ©unissez les phrases : Nous sommes arrivÃ©s. Le film avait commencÃ©.",answer:"Quand nous sommes arrivÃ©s, le film avait commencÃ©",hint:"Lâ€™action antÃ©rieure utilise le plus-que-parfait."},
  {id:"b1-05",level:"B1",skill:"Verbes",mode:"fill",prompt:"Elle ne pouvait pas entrer parce quâ€™elle ___ ses clÃ©s. (perdre)",answer:"avait perdu",hint:"Perte antÃ©rieure Ã  lâ€™impossibilitÃ© passÃ©e."},
  {id:"b1-06",level:"B1",skill:"Temps",mode:"choice",prompt:"Quelle phrase exprime une action antÃ©rieure ?",answer:"Ils Ã©taient partis avant notre arrivÃ©e.",options:["Ils partaient avant notre arrivÃ©e.","Ils sont partis avant notre arrivÃ©e.","Ils Ã©taient partis avant notre arrivÃ©e."],hint:"ÃŠtre Ã  lâ€™imparfait + participe passÃ©."},
  {id:"b1-07",level:"B1",skill:"Communication",mode:"reorder",prompt:"Formulez une hypothÃ¨se rÃ©aliste.",answer:"Si jâ€™avais plus de temps je voyagerais",tokens:["voyagerais","Si","plus","jâ€™avais","temps","de","je"],hint:"Si + imparfait, conditionnel prÃ©sent."},
  {id:"b1-08",level:"B1",skill:"Verbes",mode:"fill",prompt:"Si tu mâ€™avais prÃ©venu, je ___ venu. (Ãªtre)",answer:"serais",hint:"Conditionnel passÃ© avec Ãªtre."},
  {id:"b1-09",level:"B1",skill:"Grammaire",mode:"transform",prompt:"Donnez un conseil poli : Tu dois essayer cette activitÃ©.",answer:"Tu devrais essayer cette activitÃ©",hint:"Devoir au conditionnel = conseil."},
  {id:"b1-10",level:"B1",skill:"Communication",mode:"choice",prompt:"Quelle formule aide Ã  convaincre ?",answer:"Tu pourrais essayer, câ€™est une belle occasion.",options:["Tu fais Ã§a maintenant.","Tu pourrais essayer, câ€™est une belle occasion.","Tu as faire Ã§a."],hint:"Pourrais adoucit la proposition."},
  {id:"b1-11",level:"B1",skill:"Verbes",mode:"fill",prompt:"Il faut que nous ___ Ã  lâ€™heure. (partir)",answer:"partions",hint:"Subjonctif de partir avec nous."},
  {id:"b1-12",level:"B1",skill:"Verbes",mode:"fill",prompt:"Je doute quâ€™il ___ la rÃ©ponse. (avoir)",answer:"ait",hint:"Avoir au subjonctif : quâ€™il ait."},
  {id:"b1-13",level:"B1",skill:"Grammaire",mode:"choice",prompt:"AprÃ¨s Â« bien que Â», choisissez :",answer:"Bien quâ€™il fasse froid, nous sortons.",options:["Bien quâ€™il fait froid, nous sortons.","Bien quâ€™il fasse froid, nous sortons.","Bien quâ€™il fera froid, nous sortons."],hint:"Bien que demande le subjonctif."},
  {id:"b1-14",level:"B1",skill:"Grammaire",mode:"transform",prompt:"Transformez avec Â« pour que Â» : Je rÃ©pÃ¨te. Tu comprends.",answer:"Je rÃ©pÃ¨te pour que tu comprennes",hint:"Pour que + subjonctif."},
  {id:"b1-15",level:"B1",skill:"Communication",mode:"reorder",prompt:"Construisez une opinion nuancÃ©e.",answer:"Ã€ mon avis ce projet est utile cependant il coÃ»te cher",tokens:["ce","cependant","projet","Ã€","cher","il","avis","est","mon","utile","coÃ»te"],hint:"Opinion + argument + contraste."},
  {id:"b1-16",level:"B1",skill:"Communication",mode:"choice",prompt:"Quel connecteur introduit une opposition ?",answer:"En revanche",options:["Tout dâ€™abord","En revanche","En conclusion"],hint:"Il oppose une idÃ©e Ã  la prÃ©cÃ©dente."},
  {id:"b1-17",level:"B1",skill:"Communication",mode:"fill",prompt:"Pour terminer un texte argumentatif, utilisez : ___, cette solution paraÃ®t Ã©quilibrÃ©e.",answer:"En conclusion",hint:"Connecteur de clÃ´ture."},
  {id:"b1-18",level:"B1",skill:"Temps",mode:"fill",prompt:"Quand nous Ã©tions petits, nous ___ chez nos grands-parents chaque Ã©tÃ©. (aller)",answer:"allions",hint:"Aller Ã  lâ€™imparfait avec nous."},
];

export const tcfPromptBank: Record<TcfTaskId,string[]> = {
  tache1:[
    "Invitez vos amis Ã  une fÃªte de fin dâ€™examens; prÃ©cisez date, lieu, thÃ¨me et programme.","Proposez un pique-nique et indiquez ce que chacun doit apporter.","FÃ©licitez une amie pour son mariage et proposez votre aide.","Invitez une amie Ã  un concert et donnez les informations pratiques.","Organisez une soirÃ©e cinÃ©ma et prÃ©sentez le film choisi.","Proposez un repas familial pour un anniversaire.","Invitez des amis Ã  une exposition temporaire.","Proposez de participer Ã  un festival de musique.","Organisez une randonnÃ©e Ã  vÃ©lo avec un groupe.","Proposez un programme pour cÃ©lÃ©brer le Nouvel An.","Conseillez un ami qui veut commencer le yoga.","Recommandez un coiffeur et expliquez pourquoi.","Aidez une amie Ã  choisir un ordinateur portable.","Conseillez un dÃ©butant qui veut apprendre Ã  cuisiner.","Recommandez un lieu calme pour Ã©tudier.","Donnez des conseils avant dâ€™adopter un animal.","Proposez des mÃ©thodes pour amÃ©liorer son franÃ§ais.","SuggÃ©rez trois activitÃ©s pour le week-end.","Recommandez une association pour faire du bÃ©nÃ©volat.","Proposez une idÃ©e de cadeau original.","RÃ©digez une annonce pour vendre des meubles.","Signalez un problÃ¨me de sÃ©curitÃ© dans votre immeuble.","RÃ©digez une annonce pour chercher un colocataire.","Ã‰crivez poliment Ã  un voisin au sujet du bruit.","Organisez une fÃªte des voisins.","Demandez des conseils pour un voyage en France.","Racontez briÃ¨vement un sÃ©jour et recommandez la destination.","PrÃ©parez un programme pour la visite dâ€™un ami.","Recommandez un restaurant rÃ©cemment dÃ©couvert.","Proposez un voyage en voiture avec des amis.","Donnez des conseils pour un Ã©change linguistique.","PrÃ©sentez un musÃ©e qui mÃ©rite une visite.","Expliquez quelques aspects de la culture quÃ©bÃ©coise.","Racontez un spectacle de danse traditionnelle Ã  une amie.","Conseillez une personne qui prÃ©pare un voyage humanitaire.","Annoncez la rÃ©ussite dâ€™un examen et racontez vos efforts.","PrÃ©sentez une occasion de stage intÃ©ressante.","Racontez une confÃ©rence sur lâ€™intelligence artificielle.","Donnez des conseils pour prÃ©parer un entretien dâ€™embauche.","Recommandez une sÃ©rie rÃ©cemment dÃ©couverte.","RÃ©digez une annonce pour chercher un vÃ©lo dâ€™occasion.","Recommandez un jeu vidÃ©o et expliquez son intÃ©rÃªt.","Invitez Ã  une action de nettoyage Ã©cologique.","Partagez des gestes simples pour Ã©conomiser lâ€™Ã©nergie."
  ],
  tache2:[
    "Racontez une randonnÃ©e guidÃ©e dans un parc canadien.","PrÃ©sentez un cours de danse dÃ©couvert rÃ©cemment.","Racontez un week-end sans technologie.","Donnez votre avis sur un film indÃ©pendant vu dans un cinÃ©ma local.","PrÃ©sentez un nouveau marchÃ© biologique.","Racontez un atelier consacrÃ© Ã  la gestion du stress.","Partagez une expÃ©rience dans un atelier de peinture.","Racontez une journÃ©e sportive organisÃ©e par votre Ã©tablissement.","PrÃ©sentez une dÃ©couverte culinaire faite avec un ami Ã©tranger.","Racontez un atelier de fabrication de fromage.","DÃ©crivez une exposition de photographies historiques.","Expliquez les effets de repas familiaux sans tÃ©lÃ©phone.","Racontez un cours de yoga en plein air.","PrÃ©sentez un atelier de cosmÃ©tiques naturels.","Racontez un festival de cinÃ©ma international.","Expliquez pourquoi vous avez adoptÃ© le vÃ©lo.","Partagez une expÃ©rience dans une banque alimentaire.","Racontez votre premiÃ¨re expÃ©rience de paddle.","PrÃ©sentez un atelier de jardinage urbain.","DÃ©crivez une visite dans un musÃ©e dâ€™art moderne.","PrÃ©sentez un cafÃ© littÃ©raire de votre quartier.","Partagez les idÃ©es dâ€™une confÃ©rence sur lâ€™entrepreneuriat.","Racontez une sÃ©ance de mÃ©ditation en forÃªt.","Expliquez comment vous avez rÃ©duit votre consommation de plastique.","PrÃ©sentez un nouveau centre culturel.","Racontez une soirÃ©e de dÃ©gustation de thÃ©.","PrÃ©sentez une application de coaching sportif testÃ©e rÃ©cemment.","Racontez une visite dans un parc consacrÃ© Ã  la biodiversitÃ©.","Donnez votre avis sur un spectacle dâ€™humour amateur.","Racontez une semaine sans tÃ©lÃ©vision ni plateformes vidÃ©o.","PrÃ©sentez un atelier de poterie.","Racontez la dÃ©couverte dâ€™un restaurant de cuisine fusion.","PrÃ©sentez une initiation Ã  la permaculture.","Expliquez le fonctionnement dâ€™une bibliothÃ¨que dâ€™outils.","Racontez un atelier de rÃ©paration dâ€™objets."
  ],
  tache3:[
    "La prÃ©sence dâ€™un animal domestique dans une famille.","Les devoirs scolaires aprÃ¨s la classe.","La micro-sieste en entreprise.","Les jeux vidÃ©o dans le quotidien des enfants.","Les achats en ligne.","La vie en colocation.","Lâ€™enseignement Ã  domicile.","Le cadre de vie Ã  la campagne.","Les Ã©changes de services entre voisins.","Les activitÃ©s artistiques aprÃ¨s lâ€™Ã©cole.","Les espaces verts en ville.","Lâ€™alimentation biologique au quotidien.","Les Ã©vÃ©nements culturels locaux.","Les plateformes de streaming.","Le tÃ©lÃ©travail.","Les cours de langues en ligne.","Les vÃ©los en libre-service.","Les ateliers de cuisine pour adultes.","Les potagers urbains partagÃ©s.","Le bÃ©nÃ©volat au sein dâ€™associations.","Les formations professionnelles courtes.","Le covoiturage domicile-travail.","Les restaurants Ã  thÃ¨me.","Les brocantes et vide-greniers.","Les repas vÃ©gÃ©tariens Ã  la cantine.","Les bibliothÃ¨ques municipales.","Les animations sportives de quartier.","Les stages dâ€™Ã©tÃ© pour adolescents.","La rÃ©duction de lâ€™usage des rÃ©seaux sociaux.","Les ateliers de recyclage et de rÃ©paration.","Les vacances solidaires.","Les maisons dâ€™hÃ´tes.","Lâ€™accueil dâ€™Ã©tudiants Ã©trangers.","Les concours artistiques amateurs.","Les programmes dâ€™Ã©changes internationaux."
  ]
};

export const tcfDrills: TcfDrill[] = [
  {task:"tache1",prompt:"Quelle ouverture convient Ã  un message adressÃ© Ã  un ami ?",answer:"Salut LÃ©a, jâ€™espÃ¨re que tu vas bien.",options:["Madame, Monsieur,","Salut LÃ©a, jâ€™espÃ¨re que tu vas bien.","En conclusion,"],note:"Adaptez toujours le registre au destinataire."},
  {task:"tache1",prompt:"AprÃ¨s les dÃ©tails dâ€™une invitation, que faut-il ajouter ?",answer:"Une invitation Ã  rÃ©pondre",options:["Une nouvelle introduction","Une invitation Ã  rÃ©pondre","Une opinion contraire"],note:"Terminez lâ€™Ã©change: Â« Dis-moi si tu es disponible. Â»"},
  {task:"tache1",prompt:"Quel Ã©lÃ©ment est indispensable dans un courriel ?",answer:"Un objet clair",options:["Un titre littÃ©raire","Un objet clair","Deux arguments opposÃ©s"],note:"Lâ€™objet annonce immÃ©diatement le but du message."},
  {task:"tache2",prompt:"Quel ordre organise le mieux un rÃ©cit ?",answer:"Contexte, Ã©tapes, moment marquant, bilan",options:["Bilan, titre, contexte","Contexte, Ã©tapes, moment marquant, bilan","Opinion, synthÃ¨se, salutation"],note:"Le lecteur doit suivre lâ€™expÃ©rience sans revenir en arriÃ¨re."},
  {task:"tache2",prompt:"Quel connecteur introduit naturellement la deuxiÃ¨me Ã©tape ?",answer:"Ensuite",options:["Cependant","Ensuite","En somme"],note:"Utilisez des connecteurs chronologiques variÃ©s."},
  {task:"tache2",prompt:"Quelle conclusion est la plus adaptÃ©e ?",answer:"Je recommande vivement cette activitÃ©.",options:["Bonjour Ã  tous,","Dâ€™un cÃ´tÃ©â€¦","Je recommande vivement cette activitÃ©."],note:"La conclusion rÃ©sume lâ€™impression et ouvre sur une recommandation."},
  {task:"tache3",prompt:"Dans la synthÃ¨se, pouvez-vous donner votre opinion ?",answer:"Non, elle doit rester neutre.",options:["Oui, dÃ¨s la premiÃ¨re phrase.","Non, elle doit rester neutre.","Seulement avec Â« je pense Â»."],note:"Lâ€™opinion personnelle appartient Ã  la deuxiÃ¨me partie."},
  {task:"tache3",prompt:"Quel connecteur oppose les deux documents ?",answer:"En revanche",options:["Tout dâ€™abord","En revanche","Par exemple"],note:"Reliez les perspectives au lieu de faire deux rÃ©sumÃ©s isolÃ©s."},
  {task:"tache3",prompt:"Quelle rÃ©partition respecte la consigne ?",answer:"40-60 mots de synthÃ¨se et 80-120 mots dâ€™opinion",options:["100 mots de synthÃ¨se seulement","40-60 mots de synthÃ¨se et 80-120 mots dâ€™opinion","60 mots au total"],note:"La longueur totale attendue est de 120 Ã  180 mots."},
];
