"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { courseExercises, lessons, tcfDrills, tcfPromptBank } from "./curriculum";
import { stories } from "./stories";
import { lexicalPatterns, subjectLabels, type Subject, type Tense, verbs } from "./verbs";
import { identify, loadCloudState, readSession, saveCloudState, sendMagicLink, supabaseConfigured, type CloudSession } from "./supabase-client";

type Card = { id: string; level: "A1" | "A2"; unit: string; type: "vocabulaire" | "structure" | "prononciation"; prompt: string; answer: string; hint: string; translationEn?: string; translationEs?: string };
type Memory = Record<string, { due: number; interval: number; ease: number; reviews: number }>;
type SavedProgress = { memory: Memory; streak: number; todayReviews: number };
type RecognitionEventLike = { results: { [key: number]: { [key: number]: { transcript: string } } } };
type RecognitionLike = { lang: string; interimResults: boolean; onstart: () => void; onend: () => void; onresult: (event: RecognitionEventLike) => void; onerror: () => void; start: () => void };
type PracticeCategory = "verbes" | "nombres" | "jours" | "mois";
type PracticeItem = { sentence: string; answer: string; cue: string; infinitive?: string; en?: string; es?: string };
type TcfTaskId = "tache1" | "tache2" | "tache3";
type TcfTask = { id: TcfTaskId; number: string; title: string; words: string; min: number; max: number; goal: string; steps: string[]; phrases: string[]; topics: string[] };

const cards: Card[] = [
  {id:"a1-01",level:"A1",unit:"Premiers repÃ¨res",type:"vocabulaire",prompt:"lunes",answer:"lundi",hint:"Les jours de la semaine"},
  {id:"a1-02",level:"A1",unit:"Premiers repÃ¨res",type:"vocabulaire",prompt:"miÃ©rcoles",answer:"mercredi",hint:"Les jours de la semaine"},
  {id:"a1-03",level:"A1",unit:"Premiers repÃ¨res",type:"vocabulaire",prompt:"enero",answer:"janvier",hint:"Les mois de lâ€™annÃ©e"},
  {id:"a1-04",level:"A1",unit:"Premiers repÃ¨res",type:"vocabulaire",prompt:"ochenta",answer:"quatre-vingts",hint:"Les nombres"},
  {id:"a1-05",level:"A1",unit:"Premiers repÃ¨res",type:"structure",prompt:"Â¿QuÃ© dÃ­a es hoy?",answer:"Quel jour sommes-nous ?",hint:"La date"},
  {id:"a1-06",level:"A1",unit:"Premiers repÃ¨res",type:"prononciation",prompt:"Escucha y repite",answer:"aujourdâ€™hui",hint:"El sonido /Ê’/ aparece dos veces"},
  {id:"a1-07",level:"A1",unit:"Se prÃ©senter",type:"structure",prompt:"Me llamo Alice.",answer:"Je mâ€™appelle Alice.",hint:"PrÃ©sentation de soi"},
  {id:"a1-08",level:"A1",unit:"Se prÃ©senter",type:"structure",prompt:"Soy canadiense.",answer:"Je suis canadienne.",hint:"ÃŠtre + nationalitÃ©"},
  {id:"a1-09",level:"A1",unit:"Se prÃ©senter",type:"vocabulaire",prompt:"un profesor / una profesora",answer:"un professeur / une professeure",hint:"La profession"},
  {id:"a1-10",level:"A1",unit:"Se prÃ©senter",type:"structure",prompt:"Ella es amable.",answer:"Elle est gentille.",hint:"Adjectif au fÃ©minin"},
  {id:"a1-11",level:"A1",unit:"Se prÃ©senter",type:"structure",prompt:"Vivo en Montreal.",answer:"Jâ€™habite Ã  MontrÃ©al.",hint:"PrÃ©position + ville"},
  {id:"a1-12",level:"A1",unit:"Se prÃ©senter",type:"structure",prompt:"Voy a casa de Paul.",answer:"Je vais chez Paul.",hint:"Chez + personne"},
  {id:"a1-13",level:"A1",unit:"Se prÃ©senter",type:"structure",prompt:"Es mi libro.",answer:"Câ€™est mon livre.",hint:"Le possessif"},
  {id:"a1-14",level:"A1",unit:"Se prÃ©senter",type:"structure",prompt:"Son las tres y cuarto.",answer:"Il est trois heures et quart.",hint:"Lâ€™heure"},
  {id:"a1-15",level:"A1",unit:"Avoir & demander",type:"structure",prompt:"Tengo 30 aÃ±os.",answer:"Jâ€™ai trente ans.",hint:"En franÃ§ais, on utilise avoir"},
  {id:"a1-16",level:"A1",unit:"Avoir & demander",type:"structure",prompt:"No tengo automÃ³vil.",answer:"Je nâ€™ai pas de voiture.",hint:"NÃ©gation : pas de"},
  {id:"a1-17",level:"A1",unit:"Avoir & demander",type:"structure",prompt:"Â¿DÃ³nde trabajas?",answer:"OÃ¹ est-ce que tu travailles ?",hint:"Lâ€™interrogation"},
  {id:"a1-18",level:"A1",unit:"Avoir & demander",type:"structure",prompt:"Â¿Por quÃ© estudias francÃ©s?",answer:"Pourquoi est-ce que tu Ã©tudies le franÃ§ais ?",hint:"Mot interrogatif"},
  {id:"a1-19",level:"A1",unit:"Avoir & demander",type:"vocabulaire",prompt:"algo de pan",answer:"du pain",hint:"Article partitif masculin"},
  {id:"a1-20",level:"A1",unit:"Avoir & demander",type:"vocabulaire",prompt:"algo de agua",answer:"de lâ€™eau",hint:"Article partitif devant voyelle"},
  {id:"a1-21",level:"A1",unit:"La cuisine",type:"vocabulaire",prompt:"cortar las verduras",answer:"couper les lÃ©gumes",hint:"Ã€ la cuisine"},
  {id:"a1-22",level:"A1",unit:"La cuisine",type:"vocabulaire",prompt:"cocinar / hacer cocer",answer:"faire cuire",hint:"Ã€ la cuisine"},
  {id:"a1-23",level:"A1",unit:"La cuisine",type:"structure",prompt:"Comemos en casa.",answer:"Nous mangeons Ã  la maison.",hint:"Verbe en -ER"},
  {id:"a1-24",level:"A1",unit:"La cuisine",type:"prononciation",prompt:"Escucha y distingue: u / ou",answer:"tu â€” tout",hint:"Labios muy redondeados para /y/"},
  {id:"a2-01",level:"A2",unit:"Pouvoir, vouloir, devoir",type:"structure",prompt:"Puedo ayudarte.",answer:"Je peux tâ€™aider.",hint:"Pouvoir au prÃ©sent"},
  {id:"a2-02",level:"A2",unit:"Pouvoir, vouloir, devoir",type:"structure",prompt:"Quisiera un cafÃ©.",answer:"Je voudrais un cafÃ©.",hint:"Demande polie"},
  {id:"a2-03",level:"A2",unit:"Pouvoir, vouloir, devoir",type:"structure",prompt:"Debemos salir ahora.",answer:"Nous devons partir maintenant.",hint:"Devoir au prÃ©sent"},
  {id:"a2-04",level:"A2",unit:"Pouvoir, vouloir, devoir",type:"structure",prompt:"Â¿Puede repetir, por favor?",answer:"Pouvez-vous rÃ©pÃ©ter, sâ€™il vous plaÃ®t ?",hint:"Demander un service"},
  {id:"a2-05",level:"A2",unit:"Pouvoir, vouloir, devoir",type:"structure",prompt:"Â¿DÃ³nde puedo encontrar informaciÃ³n?",answer:"OÃ¹ puis-je trouver des renseignements ?",hint:"Obtenir de lâ€™information"},
  {id:"a2-06",level:"A2",unit:"Verbes au prÃ©sent",type:"structure",prompt:"Elegimos el tren.",answer:"Nous choisissons le train.",hint:"Choisir au prÃ©sent"},
  {id:"a2-07",level:"A2",unit:"Verbes au prÃ©sent",type:"structure",prompt:"Terminan a las cinco.",answer:"Ils finissent Ã  cinq heures.",hint:"Finir au prÃ©sent"},
  {id:"a2-08",level:"A2",unit:"Verbes au prÃ©sent",type:"structure",prompt:"Tomo el autobÃºs.",answer:"Je prends lâ€™autobus.",hint:"Prendre au prÃ©sent"},
  {id:"a2-09",level:"A2",unit:"Verbes au prÃ©sent",type:"structure",prompt:"Ella viene maÃ±ana.",answer:"Elle vient demain.",hint:"Venir au prÃ©sent"},
  {id:"a2-10",level:"A2",unit:"Verbes au prÃ©sent",type:"structure",prompt:"No entiendo la pregunta.",answer:"Je ne comprends pas la question.",hint:"NÃ©gation"},
  {id:"a2-11",level:"A2",unit:"Plans & pronoms",type:"structure",prompt:"Vamos al mercado.",answer:"Nous allons au marchÃ©.",hint:"Aller au prÃ©sent"},
  {id:"a2-12",level:"A2",unit:"Plans & pronoms",type:"structure",prompt:"Voy a llamar a Marie.",answer:"Je vais appeler Marie.",hint:"Futur proche"},
  {id:"a2-13",level:"A2",unit:"Plans & pronoms",type:"structure",prompt:"Lo conozco.",answer:"Je le connais.",hint:"Pronom complÃ©ment direct"},
  {id:"a2-14",level:"A2",unit:"Plans & pronoms",type:"structure",prompt:"Le hablo.",answer:"Je lui parle.",hint:"Pronom complÃ©ment indirect"},
  {id:"a2-15",level:"A2",unit:"Plans & pronoms",type:"structure",prompt:"Los invitamos maÃ±ana.",answer:"Nous les invitons demain.",hint:"Pronom avant le verbe"},
  {id:"a2-16",level:"A2",unit:"Temps & comparaison",type:"structure",prompt:"Trabajo desde hace dos aÃ±os.",answer:"Je travaille depuis deux ans.",hint:"Action toujours en cours"},
  {id:"a2-17",level:"A2",unit:"Temps & comparaison",type:"structure",prompt:"Me voy por tres semanas.",answer:"Je pars pour trois semaines.",hint:"DurÃ©e prÃ©vue"},
  {id:"a2-18",level:"A2",unit:"Temps & comparaison",type:"structure",prompt:"Este libro es mÃ¡s interesante.",answer:"Ce livre est plus intÃ©ressant.",hint:"Comparatif"},
  {id:"a2-19",level:"A2",unit:"Temps & comparaison",type:"structure",prompt:"Es la ciudad mÃ¡s grande.",answer:"Câ€™est la plus grande ville.",hint:"Superlatif"},
  {id:"a2-20",level:"A2",unit:"Temps & comparaison",type:"structure",prompt:"Me levanto a las siete.",answer:"Je me lÃ¨ve Ã  sept heures.",hint:"Verbe pronominal"},
  {id:"a2-21",level:"A2",unit:"Le passÃ© composÃ©",type:"structure",prompt:"He terminado mi trabajo.",answer:"Jâ€™ai fini mon travail.",hint:"Avoir + participe passÃ©"},
  {id:"a2-22",level:"A2",unit:"Le passÃ© composÃ©",type:"structure",prompt:"Vimos la pelÃ­cula.",answer:"Nous avons vu le film.",hint:"Participe passÃ© irrÃ©gulier"},
  {id:"a2-23",level:"A2",unit:"Le passÃ© composÃ©",type:"structure",prompt:"Ella llegÃ³ ayer.",answer:"Elle est arrivÃ©e hier.",hint:"ÃŠtre + accord au fÃ©minin"},
  {id:"a2-24",level:"A2",unit:"Le passÃ© composÃ©",type:"structure",prompt:"No salieron.",answer:"Ils ne sont pas sortis.",hint:"NÃ©gation autour de lâ€™auxiliaire"},
  {id:"a2-25",level:"A2",unit:"Le passÃ© composÃ©",type:"prononciation",prompt:"Escucha y repite",answer:"Jâ€™ai eu beaucoup de travail.",hint:"EnchaÃ®ne : jâ€™aiâ€¿eu"},
];

const verbCards: Card[] = [
  {id:"verb-01",level:"A1",unit:"Verbes essentiels",type:"vocabulaire",prompt:"Ãªtre",answer:"Ãªtre",hint:"Verbe essentiel",translationEn:"to be",translationEs:"ser / estar"},
  {id:"verb-02",level:"A1",unit:"Verbes essentiels",type:"vocabulaire",prompt:"avoir",answer:"avoir",hint:"Verbe essentiel",translationEn:"to have",translationEs:"tener"},
  {id:"verb-03",level:"A1",unit:"Verbes essentiels",type:"vocabulaire",prompt:"aller",answer:"aller",hint:"Verbe essentiel",translationEn:"to go",translationEs:"ir"},
  {id:"verb-04",level:"A1",unit:"Verbes essentiels",type:"vocabulaire",prompt:"pouvoir",answer:"pouvoir",hint:"Verbe essentiel",translationEn:"can / to be able to",translationEs:"poder"},
  {id:"verb-05",level:"A1",unit:"Verbes essentiels",type:"vocabulaire",prompt:"vouloir",answer:"vouloir",hint:"Verbe essentiel",translationEn:"to want",translationEs:"querer"},
  {id:"verb-06",level:"A1",unit:"Verbes essentiels",type:"vocabulaire",prompt:"devoir",answer:"devoir",hint:"Verbe essentiel",translationEn:"must / to have to",translationEs:"deber / tener que"},
  {id:"verb-07",level:"A1",unit:"Verbes essentiels",type:"vocabulaire",prompt:"finir",answer:"finir",hint:"Verbe essentiel",translationEn:"to finish",translationEs:"terminar"},
  {id:"verb-08",level:"A1",unit:"Verbes essentiels",type:"vocabulaire",prompt:"choisir",answer:"choisir",hint:"Verbe essentiel",translationEn:"to choose",translationEs:"elegir"},
  {id:"verb-09",level:"A1",unit:"Verbes essentiels",type:"vocabulaire",prompt:"prendre",answer:"prendre",hint:"Verbe essentiel",translationEn:"to take",translationEs:"tomar"},
  {id:"verb-10",level:"A1",unit:"Verbes essentiels",type:"vocabulaire",prompt:"venir",answer:"venir",hint:"Verbe essentiel",translationEn:"to come",translationEs:"venir"},
  {id:"verb-11",level:"A2",unit:"Verbes essentiels",type:"vocabulaire",prompt:"comprendre",answer:"comprendre",hint:"Verbe essentiel",translationEn:"to understand",translationEs:"comprender"},
  {id:"verb-12",level:"A1",unit:"Verbes essentiels",type:"vocabulaire",prompt:"parler",answer:"parler",hint:"Verbe essentiel",translationEn:"to speak",translationEs:"hablar"},
  {id:"verb-13",level:"A1",unit:"Verbes essentiels",type:"vocabulaire",prompt:"manger",answer:"manger",hint:"Verbe essentiel",translationEn:"to eat",translationEs:"comer"},
  {id:"verb-14",level:"A2",unit:"Verbes essentiels",type:"vocabulaire",prompt:"se lever",answer:"se lever",hint:"Verbe pronominal",translationEn:"to get up",translationEs:"levantarse"},
  {id:"verb-15",level:"A1",unit:"Verbes essentiels",type:"vocabulaire",prompt:"faire",answer:"faire",hint:"Verbe essentiel",translationEn:"to do / to make",translationEs:"hacer"},
];

const practiceSets: Record<PracticeCategory, PracticeItem[]> = {
  verbes: [
    {sentence:"Je ___ canadienne.",answer:"suis",cue:"Ãªtre Â· je",infinitive:"Ãªtre",en:"to be",es:"ser / estar"},
    {sentence:"Nous ___ un cours demain.",answer:"avons",cue:"avoir Â· nous",infinitive:"avoir",en:"to have",es:"tener"},
    {sentence:"Tu ___ au marchÃ© le samedi.",answer:"vas",cue:"aller Â· tu",infinitive:"aller",en:"to go",es:"ir"},
    {sentence:"Vous ___ rÃ©pÃ©ter, sâ€™il vous plaÃ®t ?",answer:"pouvez",cue:"pouvoir Â· vous",infinitive:"pouvoir",en:"can / to be able to",es:"poder"},
    {sentence:"Ils ___ apprendre le franÃ§ais.",answer:"veulent",cue:"vouloir Â· ils",infinitive:"vouloir",en:"to want",es:"querer"},
    {sentence:"Je ___ partir maintenant.",answer:"dois",cue:"devoir Â· je",infinitive:"devoir",en:"must / to have to",es:"deber / tener que"},
    {sentence:"Elle ___ son travail Ã  cinq heures.",answer:"finit",cue:"finir Â· elle",infinitive:"finir",en:"to finish",es:"terminar"},
    {sentence:"Nous ___ le train.",answer:"choisissons",cue:"choisir Â· nous",infinitive:"choisir",en:"to choose",es:"elegir"},
    {sentence:"Je ___ lâ€™autobus chaque matin.",answer:"prends",cue:"prendre Â· je",infinitive:"prendre",en:"to take",es:"tomar"},
    {sentence:"Marie ___ demain soir.",answer:"vient",cue:"venir Â· elle",infinitive:"venir",en:"to come",es:"venir"},
    {sentence:"Vous ___ la question ?",answer:"comprenez",cue:"comprendre Â· vous",infinitive:"comprendre",en:"to understand",es:"comprender"},
    {sentence:"Nous ___ franÃ§ais Ã  la maison.",answer:"parlons",cue:"parler Â· nous",infinitive:"parler",en:"to speak",es:"hablar"},
    {sentence:"Tu ___ avec tes amis.",answer:"manges",cue:"manger Â· tu",infinitive:"manger",en:"to eat",es:"comer"},
    {sentence:"Je me ___ Ã  sept heures.",answer:"lÃ¨ve",cue:"se lever Â· je",infinitive:"se lever",en:"to get up",es:"levantarse"},
    {sentence:"Ils ___ la cuisine ensemble.",answer:"font",cue:"faire Â· ils",infinitive:"faire",en:"to do / to make",es:"hacer"},
  ],
  nombres: [
    {sentence:"Jâ€™ai ___ ans.",answer:"dix-huit",cue:"18"},{sentence:"Nous sommes ___ personnes.",answer:"vingt",cue:"20"},
    {sentence:"Le billet coÃ»te ___ dollars.",answer:"trente",cue:"30"},{sentence:"Il y a ___ Ã©tudiants.",answer:"quarante",cue:"40"},
    {sentence:"Elle a ___ livres.",answer:"cinquante",cue:"50"},{sentence:"Le voyage dure ___ minutes.",answer:"soixante",cue:"60"},
    {sentence:"La salle compte ___ places.",answer:"soixante-dix",cue:"70"},{sentence:"Mon grand-pÃ¨re a ___ ans.",answer:"quatre-vingts",cue:"80"},
    {sentence:"Le train roule Ã  ___ kilomÃ¨tres-heure.",answer:"quatre-vingt-dix",cue:"90"},{sentence:"Le livre a ___ pages.",answer:"cent",cue:"100"},
    {sentence:"Nous avons ___ rendez-vous.",answer:"deux",cue:"2"},{sentence:"Elle travaille ___ jours.",answer:"cinq",cue:"5"},
    {sentence:"Il est ___ heures.",answer:"huit",cue:"8"},{sentence:"Le cours commence Ã  ___ heures.",answer:"neuf",cue:"9"},
    {sentence:"Jâ€™habite au numÃ©ro ___.",answer:"douze",cue:"12"},{sentence:"Le mois a ___ jours.",answer:"trente et un",cue:"31"},
  ],
  jours: [
    {sentence:"La semaine commence le ___.",answer:"lundi",cue:"lunes"},{sentence:"AprÃ¨s lundi, câ€™est ___.",answer:"mardi",cue:"martes"},
    {sentence:"Le milieu de la semaine est ___.",answer:"mercredi",cue:"miÃ©rcoles"},{sentence:"AprÃ¨s mercredi, câ€™est ___.",answer:"jeudi",cue:"jueves"},
    {sentence:"Le dernier jour de travail est souvent ___.",answer:"vendredi",cue:"viernes"},{sentence:"Le week-end commence le ___.",answer:"samedi",cue:"sÃ¡bado"},
    {sentence:"Le jour avant lundi est ___.",answer:"dimanche",cue:"domingo"},
  ],
  mois: [
    {sentence:"Lâ€™annÃ©e commence en ___.",answer:"janvier",cue:"enero"},{sentence:"Le mois aprÃ¨s janvier est ___.",answer:"fÃ©vrier",cue:"febrero"},
    {sentence:"Le printemps commence en ___.",answer:"mars",cue:"marzo"},{sentence:"AprÃ¨s mars, câ€™est ___.",answer:"avril",cue:"abril"},
    {sentence:"Le mois avant juin est ___.",answer:"mai",cue:"mayo"},{sentence:"Lâ€™Ã©tÃ© commence en ___.",answer:"juin",cue:"junio"},
    {sentence:"La fÃªte du Canada est en ___.",answer:"juillet",cue:"julio"},{sentence:"AprÃ¨s juillet, câ€™est ___.",answer:"aoÃ»t",cue:"agosto"},
    {sentence:"Les cours reprennent en ___.",answer:"septembre",cue:"septiembre"},{sentence:"Lâ€™Halloween est en ___.",answer:"octobre",cue:"octubre"},
    {sentence:"AprÃ¨s octobre, câ€™est ___.",answer:"novembre",cue:"noviembre"},{sentence:"NoÃ«l est en ___.",answer:"dÃ©cembre",cue:"diciembre"},
  ],
};

const practiceMeta: Record<PracticeCategory,{title:string;icon:string;description:string}> = {
  verbes:{title:"Verbes",icon:"V",description:"Conjuguez dans une phrase"},
  nombres:{title:"Nombres",icon:"12",description:"Ã‰crivez les nombres en lettres"},
  jours:{title:"Jours",icon:"J",description:"Retrouvez les jours de la semaine"},
  mois:{title:"Mois",icon:"M",description:"ComplÃ©tez les mois de lâ€™annÃ©e"},
};

const tcfTasks: TcfTask[] = [
  {id:"tache1",number:"01",title:"Le message",words:"60 Ã  120 mots",min:60,max:120,goal:"Raconter, dÃ©crire ou expliquer clairement Ã  un destinataire prÃ©cis.",steps:["Salutation et objet du message","Annonce rapide de la raison","Informations utiles et dÃ©tails concrets","Invitation Ã  rÃ©pondre","Formule finale et signature"],phrases:["Je tâ€™Ã©cris pour te parler deâ€¦","Que dirais-tu deâ€¦ ?","Je te recommande vivement deâ€¦","Fais-moi savoir ce que tu en penses.","Nâ€™hÃ©site pas Ã  mâ€™Ã©crire.","Ã€ trÃ¨s bientÃ´t,"],topics:["Invitez des amis Ã  une fÃªte de fin dâ€™examens avec une date, un lieu et un thÃ¨me.","Proposez un pique-nique et prÃ©cisez le programme et ce que chacun doit apporter.","Conseillez un ami qui souhaite amÃ©liorer son franÃ§ais.","Recommandez une activitÃ© culturelle dÃ©couverte rÃ©cemment.","Ã‰crivez Ã  un voisin pour rÃ©soudre poliment un problÃ¨me de bruit.","Cherchez un colocataire et prÃ©sentez le logement et vos attentes.","Invitez un groupe Ã  participer Ã  une action Ã©cologique.","Demandez des conseils pour prÃ©parer un voyage au Canada."]},
  {id:"tache2",number:"02",title:"Le rÃ©cit",words:"120 Ã  150 mots",min:120,max:150,goal:"Raconter une expÃ©rience, exprimer ses impressions et donner envie de la dÃ©couvrir.",steps:["Titre accrocheur","Introduction et contexte","DÃ©roulement en plusieurs Ã©tapes","Moment marquant et Ã©motions","Conclusion et recommandation"],phrases:["RÃ©cemment, jâ€™ai eu lâ€™occasion deâ€¦","Tout dâ€™abordâ€¦ Ensuiteâ€¦ Enfinâ€¦","Ce qui mâ€™a particuliÃ¨rement marquÃ©, câ€™estâ€¦","Ã€ ma grande surpriseâ€¦","Cette expÃ©rience mâ€™a permis deâ€¦","Je recommande vivement cette activitÃ©."],topics:["Racontez une randonnÃ©e mÃ©morable dans un parc canadien.","PrÃ©sentez un atelier crÃ©atif qui vous a surpris.","DÃ©crivez une semaine avec moins dâ€™Ã©crans et ses effets.","Partagez une expÃ©rience de bÃ©nÃ©volat enrichissante.","Racontez la dÃ©couverte dâ€™un marchÃ© ou dâ€™un restaurant original.","PrÃ©sentez une activitÃ© Ã©cologique utile Ã  votre quartier.","DÃ©crivez une exposition ou un festival qui vous a marquÃ©.","Racontez une activitÃ© sportive essayÃ©e pour la premiÃ¨re fois."]},
  {id:"tache3",number:"03",title:"SynthÃ¨se & opinion",wor…7995 tokens truncated…"} onClick={()=>{setLevel("A1");setIndex(0);setRevealed(false)}}>A1</button><button className={level==="A2"?"selected":""} onClick={()=>{setLevel("A2");setIndex(0);setRevealed(false)}}>A2</button><button className={level==="Verbes"?"selected":""} onClick={()=>{setLevel("Verbes");setIndex(0);setRevealed(false)}}>Verbes</button></div>
        <article className="flashcard">
          <div className="card-meta"><span>{card.translationEn?"VERBE":card.level}</span><span>{card.type}</span><span>{card.unit}</span></div>
          <p className="prompt-label">{card.translationEn?"QUE VEUT DIRE CE VERBE ?":"DITES-LE EN FRANÃ‡AIS"}</p><h2>{card.prompt}</h2>
          {!revealed ? <button className="reveal" onClick={()=>setRevealed(true)}>Afficher la rÃ©ponse</button> : <div className="answer-zone"><div className="divider"/>{card.translationEn?<><div className="verb-translations"><div><small>ENGLISH</small><strong>{card.translationEn}</strong></div><div><small>ESPAÃ‘OL</small><strong>{card.translationEs}</strong></div></div><p className="hint">Ã‰coutez puis rÃ©pÃ©tez le verbe en franÃ§ais.</p></>:<><p className="answer">{card.answer}</p><p className="hint">{card.hint}</p></>}<audio ref={audioRef} data-speech={card.answer} className="native-audio" controls preload="metadata" src={`/audio/${card.id}.mp3`} aria-label={`Prononciation de ${card.answer}`} onPlay={()=>setAudioStatus("Lectureâ€¦")} onEnded={()=>setAudioStatus("")} onError={(event)=>speakText(event.currentTarget.dataset.speech||"",event.currentTarget.playbackRate<.9)}/><div className="audio-actions"><button onClick={()=>playAudio()}>â–¶ Ã‰couter</button><button onClick={()=>playAudio(true)}>â—Œ Plus lent</button><button className={listening?"recording":""} onClick={()=>record(card.answer)}>â— {listening?"Jâ€™Ã©couteâ€¦":"Ma voix"}</button></div>{audioStatus&&<p className="audio-status" role="status">{audioStatus}</p>}{heard&&<div className={`heard ${match?"match":""}`}><small>{match?"Lâ€™APP A ENTENDU":"AIDE MICROPHONE"}</small><p>{heard}</p>{match&&<strong>TrÃ¨s bien !</strong>}</div>}</div>}
        </article>
        {revealed && <div className="rating"><p>Comment Ã©tait votre souvenir ?</p><div><button onClick={()=>rate(1)}><span>â†º</span>Difficile</button><button onClick={()=>rate(3)}><span>â‰ˆ</span>Presque</button><button className="good" onClick={()=>rate(5)}><span>âœ“</span>Je savais</button></div></div>}
      </section>}

      {view === "practice" && <section className="practice-view">
        <div className="practice-title-row"><div><p className="eyebrow">PRATIQUE ACTIVE</p><h1>Construisez vos rÃ©flexes</h1><p className="lead">ReconnaÃ®tre, retrouver, ordonner et transformer : quatre chemins vers la mÃ©moire.</p></div><div className="practice-score"><strong>{practiceTrack==="course"?courseStats.correct:practiceScore.correct}</strong><span>/ {practiceTrack==="course"?courseStats.total:practiceScore.total}</span><small>bonnes rÃ©ponses</small></div></div>
        <div className="practice-track"><button className={practiceTrack==="course"?"selected":""} onClick={()=>{setPracticeTrack("course");resetCourseExercise()}}>Parcours complet</button><button className={practiceTrack==="reflexes"?"selected":""} onClick={()=>setPracticeTrack("reflexes")}>Verbes, nombres & calendrier</button></div>
        {practiceTrack==="course"?<>
          <div className="course-filters">{(["Tous","A1","A2","B1"] as const).map(item=><button key={item} className={courseLevel===item?"selected":""} onClick={()=>{setCourseLevel(item);setCourseIndex(0);resetCourseExercise()}}>{item==="Tous"?"Mix A1â€“B1":item}</button>)}</div>
          <article className="course-exercise"><div className="course-exercise-meta"><span>{courseExercise.level}</span><span>{courseExercise.skill}</span><small>{courseIndex%filteredCourseExercises.length+1} / {filteredCourseExercises.length}</small></div><p className="course-mode">{courseExercise.mode==="choice"?"RECONNAÃŽTRE":courseExercise.mode==="reorder"?"CONSTRUIRE":courseExercise.mode==="transform"?"TRANSFORMER":"RETROUVER"}</p><h2>{courseExercise.prompt}</h2>
            {courseExercise.mode==="choice"&&<div className="choice-options">{courseExercise.options?.map(option=><button key={option} className={courseInput===option?"selected":""} onClick={()=>{if(!courseResult)setCourseInput(option)}}>{option}</button>)}</div>}
            {courseExercise.mode==="reorder"&&<><div className="built-sentence">{courseInput||"Construisez la phraseâ€¦"}</div><div className="word-tokens">{courseExercise.tokens?.map((token,i)=><button key={`${token}-${i}`} disabled={courseSelected.includes(i)||!!courseResult} onClick={()=>{setCourseSelected(items=>[...items,i]);setCourseInput(value=>value?`${value} ${token}`:token)}}>{token}</button>)}</div><button className="clear-order" disabled={!courseInput||!!courseResult} onClick={()=>{setCourseInput("");setCourseSelected([])}}>Effacer</button></>}
            {(courseExercise.mode==="fill"||courseExercise.mode==="transform")&&<input className="course-answer" value={courseInput} onChange={event=>{setCourseInput(event.target.value);if(courseResult)setCourseResult(null)}} placeholder="Ã‰crivez votre rÃ©ponseâ€¦" autoComplete="off"/>}
            {!courseResult?<button className="check-course" disabled={!courseInput.trim()} onClick={checkCourseExercise}>VÃ©rifier</button>:<div className={`course-feedback ${courseResult}`}><strong>{courseResult==="correct"?"âœ“ TrÃ¨s bien !":"Ã€ retravailler"}</strong><span>{courseExercise.answer}</span><p>{courseExercise.hint}</p><button onClick={nextCourseExercise}>Exercice suivant â†’</button></div>}
          </article>
        </>:<>
          <div className="practice-categories">{(Object.keys(practiceMeta) as PracticeCategory[]).map(category=><button key={category} className={practiceCategory===category?"selected":""} onClick={()=>choosePractice(category)}><span>{practiceMeta[category].icon}</span><div><strong>{practiceMeta[category].title}</strong><small>{practiceMeta[category].description}</small></div></button>)}</div>
          <article className="completion-card"><div className="completion-top"><span>{practiceMeta[practiceCategory].title}</span><small>{practiceIndex+1} / {practiceSets[practiceCategory].length}</small></div><p className="practice-cue">INDICE Â· {practiceItem.cue}</p><h2>{practiceBefore}<span className="sentence-blank">_____</span>{practiceAfter}</h2>{practiceItem.infinitive&&<div className="verb-meaning"><strong>{practiceItem.infinitive}</strong><span>significado:</span><button className={meaningLang==="en"?"active":""} onClick={()=>setMeaningLang(meaningLang==="en"?null:"en")}>EN</button><button className={meaningLang==="es"?"active":""} onClick={()=>setMeaningLang(meaningLang==="es"?null:"es")}>ES</button>{meaningLang&&<small>{meaningLang==="en"?practiceItem.en:practiceItem.es}</small>}</div>}<form onSubmit={checkPractice} className="completion-form"><label htmlFor="practice-answer">Votre rÃ©ponse</label><div><input id="practice-answer" value={practiceInput} onChange={event=>{setPracticeInput(event.target.value);if(practiceResult)setPracticeResult(null)}} placeholder="Ã‰crivez le motâ€¦" autoComplete="off" autoCapitalize="none"/><button type="submit" disabled={!practiceInput.trim()}>VÃ©rifier</button></div></form><div className={`practice-feedback ${practiceResult||""}`} aria-live="polite">{practiceResult==="correct"&&<><strong>âœ“ TrÃ¨s bien !</strong><span>{practiceItem.answer}</span></>}{practiceResult==="wrong"&&<><strong>Encore un petit effort</strong><span>La rÃ©ponse est : <b>{practiceItem.answer}</b></span></>}</div>{practiceResult&&<button className="next-practice" onClick={nextPractice}>Phrase suivante â†’</button>}</article>
        </>}
      </section>}

      {view === "verbs" && <section className="verbs-view">
        <div className="verbs-heading"><div><p className="eyebrow">LABORATORIO DE CONJUGACIÃ“N</p><h1>Entiende el patrÃ³n.<br/><em>Luego prodÃºcelo.</em></h1><p>Reglas claras, prÃ¡ctica activa y repaso de las formas que cuestan.</p></div><div className="verbs-score"><strong>{verbStats.correct}</strong><span>/ {verbStats.total}<br/>correctas</span></div></div>
        <div className="verb-lab"><div className="verb-controls"><label>Verbo<select value={verbId} onChange={event=>{setVerbId(event.target.value);setVerbAnswer("");setVerbResult(null)}}>{verbs.map(item=><option key={item.id} value={item.id}>{item.infinitive} Â· {item.es}</option>)}</select></label><label>Tiempo<select value={verbTense} onChange={event=>{setVerbTense(event.target.value as Tense);setVerbAnswer("");setVerbResult(null)}}>{(["prÃ©sent","passÃ© composÃ©","imparfait","futur proche","futur simple"] as Tense[]).map(item=><option key={item}>{item}</option>)}</select></label></div><div className="verb-info"><strong>{verb.infinitive}</strong><span>EN Â· {verb.en}</span><span>ES Â· {verb.es}</span><small>PronunciaciÃ³n: {verb.pronunciation}</small><button onClick={()=>speakText(verb.infinitive)}>â–¶ Escuchar</button></div><div className="subject-grid">{(Object.keys(subjectLabels) as Subject[]).map(subject=><button key={subject} className={verbSubject===subject?"selected":""} onClick={()=>{setVerbSubject(subject);setVerbAnswer("");setVerbResult(null)}}>{subjectLabels[subject]}</button>)}</div><form className="verb-question" onSubmit={checkVerb}><p className="eyebrow">ESCRIBE LA FORMA</p><h2><mark>{verbSubject}</mark> ________</h2><small>{verbTense} Â· {verb.es}</small><input value={verbAnswer} onChange={event=>{setVerbAnswer(event.target.value);setVerbResult(null)}} placeholder="Escribe la conjugaciÃ³nâ€¦" autoComplete="off"/><button disabled={!verbAnswer.trim()}>Verificar</button>{verbResult&&<div className={`verb-feedback ${verbResult}`}><strong>{verbResult==="correct"?"âœ“ Correcto":"La forma correcta"}</strong><span>{verbSubject} <mark>{verbForm}</mark></span><p>{verbTense==="passÃ© composÃ©"?"Auxiliar + participio pasado.":verbTense==="futur proche"?"aller conjugado + infinitivo.":verbTense==="imparfait"?"Base de nous + terminaciones -ais, -ais, -aitâ€¦":verbTense==="futur simple"?"Infinitivo o raÃ­z irregular + terminaciones del futuro.":"Observa la terminaciÃ³n que cambia con la persona."}</p></div>}</form></div>
        <section className="transform-story"><p className="eyebrow">HISTORIA TRANSFORMABLE</p><h2>Una misma idea, ocho personas y cinco tiempos</h2><p className="transform-fr"><mark>{verbSubject}</mark> <mark>{verbForm}</mark> le franÃ§ais avec ses amis chaque semaine.</p><p>ES: Esta persona practica francÃ©s con sus amigos. Cambia persona y tiempo para comparar la estructura.</p><small>Las palabras resaltadas cambian al modificar el sujeto o el tiempo.</small><button onClick={()=>speakText(`${verbSubject} ${verbForm} le franÃ§ais avec ses amis chaque semaine.`)}>â–¶ Escuchar la historia</button></section>
        <section className="patterns"><p className="eyebrow">PATRONES LÃ‰XICOS</p><h2>Pistas entre espaÃ±ol y francÃ©s</h2><div>{lexicalPatterns.map(item=><article key={item.es}><strong>{item.es} â†’ {item.fr}</strong><span>{item.example}</span><small>{item.note}</small></article>)}</div></section>
      </section>}

      {view === "tcf" && <section className="tcf-view">
        <div className="tcf-heading"><div><p className="eyebrow">TCF CANADA Â· EXPRESSION Ã‰CRITE</p><h1>De la mÃ©thode<br/><em>au jour de lâ€™examen.</em></h1><p>{totalTcfTopics} sujets issus du guide, avec modÃ¨les corrigÃ©s par une mÃ©thode conforme aux limites.</p></div><div className="tcf-source"><strong>{totalTcfTopics}</strong><span>sujets<br/>Ã  pratiquer</span></div></div>
        <div className="tcf-mode-tabs">{([['method','Apprendre'],['guided','Pratique guidÃ©e'],['write','RÃ©diger'],['simulate','Simulacre']] as const).map(([id,label])=><button key={id} className={tcfMode===id?"selected":""} onClick={()=>setTcfMode(id)}>{label}</button>)}</div>
        {tcfMode!=="simulate"&&<div className="tcf-task-tabs">{tcfTasks.map(task=><button key={task.id} className={tcfTaskId===task.id?"selected":""} onClick={()=>chooseTcfTask(task.id)}><span>{task.number}</span><div><strong>{task.title}</strong><small>{task.words} Â· {tcfPromptBank[task.id].length} sujets</small></div></button>)}</div>}
        {tcfMode==="method"&&<section className="tcf-method"><div className="tcf-method-title"><div><small>OBJECTIF DE LA TÃ‚CHE {tcfTask.number}</small><h2>{tcfTask.goal}</h2></div><span>{tcfTask.words}</span></div><div className="tcf-learning-grid"><article><p className="eyebrow">STRUCTURE Ã€ RETENIR</p><ol>{tcfTask.steps.map((step,i)=><li key={step}><span>{i+1}</span>{step}</li>)}</ol></article><article><p className="eyebrow">BOÃŽTE Ã€ EXPRESSIONS</p><div className="tcf-phrases">{tcfTask.phrases.map(phrase=><span key={phrase}>{phrase}</span>)}</div></article></div></section>}
        {tcfMode==="guided"&&<section className="tcf-guided"><div className="tcf-guided-top"><span>TÃ‚CHE {tcfTask.number}</span><small>{tcfDrillIndex%taskDrills.length+1} / {taskDrills.length}</small></div><p className="eyebrow">COMPRENDRE LA MÃ‰THODE</p><h2>{tcfDrill.prompt}</h2><div className="tcf-drill-options">{tcfDrill.options.map(option=><button key={option} className={tcfDrillAnswer===option?"selected":""} disabled={!!tcfDrillAnswer} onClick={()=>setTcfDrillAnswer(option)}>{option}</button>)}</div>{tcfDrillAnswer&&<div className={`tcf-drill-feedback ${tcfDrillAnswer===tcfDrill.answer?"correct":"wrong"}`}><strong>{tcfDrillAnswer===tcfDrill.answer?"âœ“ Bonne rÃ©ponse":`RÃ©ponse : ${tcfDrill.answer}`}</strong><p>{tcfDrill.note}</p><button onClick={()=>{setTcfDrillIndex(i=>(i+1)%taskDrills.length);setTcfDrillAnswer("")}}>Question suivante â†’</button></div>}</section>}
        {tcfMode==="write"&&<section className="writing-lab"><div className="writing-lab-head"><div><p className="eyebrow">ATELIER Dâ€™Ã‰CRITURE</p><h2>Sujet {tcfTopic%tcfTopics.length+1} / {tcfTopics.length}</h2></div><button onClick={()=>{setTcfTopic(i=>(i+1)%tcfTopics.length);setTcfChecks([false,false,false,false])}}>Changer de sujet â†»</button></div><div className="writing-prompt"><span>TÃ‚CHE {tcfTask.number}</span><p>{tcfTopics[tcfTopic%tcfTopics.length]}</p></div><div className="writing-area"><label htmlFor="tcf-draft">Votre rÃ©ponse <small>Le brouillon est enregistrÃ© sur cet appareil.</small></label><textarea id="tcf-draft" value={tcfDraft} onChange={event=>updateTcfDraft(event.target.value)} placeholder="Commencez Ã  Ã©crire iciâ€¦" spellCheck="true"/><div className={`word-meter ${tcfWordState}`}><span>{tcfWordCount} mots</span><i><b style={{width:`${Math.min(100,(tcfWordCount/tcfTask.max)*100)}%`}}/></i><small>{tcfWordState==="short"?`Encore ${tcfTask.min-tcfWordCount} mots minimum`:tcfWordState==="long"?`${tcfWordCount-tcfTask.max} mots en trop`:"Longueur parfaite"}</small></div></div><div className="tcf-checklist"><p className="eyebrow">AVANT DE TERMINER</p>{["Jâ€™ai respectÃ© la consigne et le destinataire.","Mon texte suit la structure de la tÃ¢che.","Jâ€™ai utilisÃ© des connecteurs variÃ©s.","Jâ€™ai relu les accords, verbes et accents."].map((item,i)=><label key={item}><input type="checkbox" checked={tcfChecks[i]} onChange={()=>setTcfChecks(checks=>checks.map((value,j)=>j===i?!value:value))}/><span>{item}</span></label>)}</div></section>}
        {tcfMode==="simulate"&&<section className="tcf-simulator"><div className="simulator-head"><div><p className="eyebrow">SIMULACRE COMPLET</p><h2>Les trois tÃ¢ches, sans assistance</h2></div><button onClick={()=>{setTcfTopic(i=>i+1);setSimulationDrafts(["","",""])}}>Nouveau simulacre â†»</button></div><p className="simulator-note">RÃ©digez les trois rÃ©ponses. Les compteurs vÃ©rifient les longueurs; vos textes restent sur cet appareil.</p>{tcfTasks.map((task,i)=><article key={task.id}><div className="sim-task-head"><span>TÃ‚CHE {task.number}</span><strong>{task.words}</strong></div><p>{tcfPromptBank[task.id][tcfTopic%tcfPromptBank[task.id].length]}</p><textarea value={simulationDrafts[i]} onChange={event=>setSimulationDrafts(drafts=>drafts.map((draft,j)=>j===i?event.target.value:draft))} placeholder={`Votre rÃ©ponse pour la tÃ¢che ${task.number}â€¦`}/><small>{simulationCounts[i]} mots</small></article>)}</section>}
      </section>}

      {view === "themes" && <section className="inner-view"><p className="eyebrow">PARCOURS COMPLET</p><h1>Choisissez un thÃ¨me</h1><p className="lead">Les contenus A1 et A2 de vos cours, organisÃ©s pour la mÃ©moire active.</p><div className="unit-list">{units.map(key=>{const [l,u]=key.split("|");const set=cards.filter(c=>c.level===l&&c.unit===u);const done=set.filter(c=>(memory[c.id]?.reviews||0)>=2).length;return <button key={key} onClick={()=>{setLevel(l as "A1"|"A2");setIndex(cards.filter(c=>c.level===l).findIndex(c=>c.unit===u));setView("study")}}><span className="unit-level">{l}</span><div><strong>{u}</strong><small>{set.length} cartes Â· {done} acquises</small><i><b style={{width:`${done/set.length*100}%`}}/></i></div><span>â†’</span></button>})}</div></section>}

      {view === "progress" && <section className="inner-view"><p className="eyebrow">VOTRE PROGRESSION</p><h1>Chaque compÃ©tence compte</h1><p className="lead">Les leÃ§ons, les histoires, la pratique active et la rÃ©pÃ©tition espacÃ©e avancent ensemble.</p><div className="stats-grid"><article><small>LEÃ‡ONS TERMINÃ‰ES</small><strong>{completedLessons.length}</strong><span>sur {lessons.length}</span></article><article><small>HISTOIRES MÃ‰MORISÃ‰ES</small><strong>{completedStories.length}</strong><span>sur {stories.length}</span></article><article><small>PRATIQUE ACTIVE</small><strong>{courseStats.correct}</strong><span>bonnes rÃ©ponses sur {courseStats.total}</span></article><article><small>CARTES ACQUISES</small><strong>{learned}</strong><span>sur {cards.length}</span></article><article><small>SÃ‰RIE ACTUELLE</small><strong>{streak}</strong><span>jours</span></article></div><div className="memory-note"><div>âœ¦</div><div><h2>Un contenu nâ€™est maÃ®trisÃ© quâ€™aprÃ¨s lâ€™avoir produit</h2><p>Apprenez la rÃ¨gle, observez-la dans une histoire, reconstruisez les phrases, puis retrouvez-la plus tard dans les cartes.</p></div></div><button className="reset" onClick={()=>{if(confirm("Effacer tout votre progrÃ¨s ?")){localStorage.removeItem("bravo-memoire");localStorage.removeItem("bravo-lessons");localStorage.removeItem("bravo-stories");localStorage.removeItem("bravo-course-stats");setMemory({});setCompletedLessons([]);setCompletedStories([]);setCourseStats({correct:0,total:0});setTodayReviews(0);setStreak(0)}}}>Recommencer le parcours</button></section>}
    </section>

    <nav className="mobile-nav"><button className={view==="home"?"active":""} onClick={()=>setView("home")}><span>âŒ‚</span>Jour</button><button className={view==="learn"?"active":""} onClick={()=>setView("learn")}><span>â—‡</span>Apprendre</button><button className={view==="stories"?"active":""} onClick={()=>setView("stories")}><span>â—«</span>Histoires</button><button className={view==="practice"?"active":""} onClick={()=>setView("practice")}><span>âœŽ</span>Pratique</button><button className={view==="verbs"?"active":""} onClick={()=>setView("verbs")}><span>V</span>Verbos</button><button className={view==="study"?"active":""} onClick={()=>setView("study")}><span>â–±</span>RÃ©viser</button><button className={view==="tcf"?"active":""} onClick={()=>setView("tcf")}><span>TCF</span>Ã‰criture</button><button className={view==="progress"?"active":""} onClick={()=>setView("progress")}><span>â†—</span>ProgrÃ¨s</button></nav>
  </main>
}

